// auto generated by tdr 2.7.37, don't edit!
//
//	go code compiler
//	author: cowhuang@tencent.com
//
// create time: 2025-08-16 12:20:51
package client

import (
	"encoding/binary"
	"errors"

	"github.com/tencentyun/tsf4g/tdrcom"
)

// 红方英雄机器人
const IDRedHero int64 = 1

// 红方英雄机器人选手端
const ClientIDRedHero int64 = 0x0101

// 数据帧起始字节固定值
const SOF int64 = 0xA5
const (
	FrameHeaderBaseVersion    uint32 = 1
	FrameHeaderCurrentVersion uint32 = 1
)

// FrameHeader
type FrameHeader struct {
	Sof byte `tdr_field:"sof"`

	DataLength uint16 `tdr_field:"data_length"`

	Seq byte `tdr_field:"seq"`

	Crc byte `tdr_field:"crc8"`
}

func NewFrameHeader() *FrameHeader {
	obj := new(FrameHeader)
	obj.Init()
	return obj
}

func (this *FrameHeader) GetBaseVersion() uint32 {
	return FrameHeaderBaseVersion
}

func (this *FrameHeader) GetCurrentVersion() uint32 {
	return FrameHeaderCurrentVersion
}

func (this *FrameHeader) Init() {
	this.Sof = 0xA5

}

func (this *FrameHeader) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("FrameHeader Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *FrameHeader) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > FrameHeaderCurrentVersion {
		cutVer = FrameHeaderCurrentVersion
	}
	// check cut version
	if cutVer < FrameHeaderBaseVersion {
		return errors.New("FrameHeader cut version must large than FrameHeaderBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.Sof)
	if err != nil {
		return errors.New("FrameHeader.Sof pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.DataLength)
	if err != nil {
		return errors.New("FrameHeader.DataLength pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Seq)
	if err != nil {
		return errors.New("FrameHeader.Seq pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Crc)
	if err != nil {
		return errors.New("FrameHeader.Crc pack error\n" + err.Error())
	}

	return nil
}

func (this *FrameHeader) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("FrameHeader data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *FrameHeader) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > FrameHeaderCurrentVersion {
		cutVer = FrameHeaderCurrentVersion
	}
	// check version
	if cutVer < FrameHeaderBaseVersion {
		errors.New("FrameHeader cut version must large than FrameHeaderBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.Sof)
	if err != nil {
		return errors.New("FrameHeader.Sof unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.DataLength)
	if err != nil {
		return errors.New("FrameHeader.DataLength unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Seq)
	if err != nil {
		return errors.New("FrameHeader.Seq unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Crc)
	if err != nil {
		return errors.New("FrameHeader.Crc unpack error\n" + err.Error())
	}

	return err
}

// 比赛状态数据，固定以 1Hz 频率发送
const CmdGameState int64 = 0x0001

// 比赛结果数据，比赛结束触发发送
const CmdGameResult int64 = 0x0002

// 机器人血量数据，固定以 3Hz 频率发送
const CmdRobotHealth int64 = 0x0003

// 数据帧中 data 的最大长度
const DataMaxLength int64 = 1024
const (
	FrameBaseVersion    uint32 = 1
	FrameCurrentVersion uint32 = 1
)

// Frame
type Frame struct {
	FrameHeader *FrameHeader `tdr_field:"frame_header"`

	CmdId uint16 `tdr_field:"cmd_id"`

	Data []byte `tdr_field:"data" tdr_count:"1024"`

	FrameTail uint16 `tdr_field:"frame_tail"`
}

func NewFrame() *Frame {
	obj := new(Frame)
	obj.Init()
	return obj
}

func (this *Frame) GetBaseVersion() uint32 {
	return FrameBaseVersion
}

func (this *Frame) GetCurrentVersion() uint32 {
	return FrameCurrentVersion
}

func (this *Frame) Init() {
	this.FrameHeader = NewFrameHeader()

}

func (this *Frame) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("Frame Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *Frame) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > FrameCurrentVersion {
		cutVer = FrameCurrentVersion
	}
	// check cut version
	if cutVer < FrameBaseVersion {
		return errors.New("Frame cut version must large than FrameBaseVersion\n")
	}

	var err error

	err = this.FrameHeader.PackTo(cutVer, w)
	if err != nil {
		return errors.New("Frame.FrameHeader pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.CmdId)
	if err != nil {
		return errors.New("Frame.CmdId pack error\n" + err.Error())
	}

	if len(this.Data) != int(1024) {
		return errors.New("Frame.Data's length should = 1024")
	}
	err = binary.Write(w, binary.BigEndian, this.Data[:])
	if err != nil {
		return errors.New("Frame.Data pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.FrameTail)
	if err != nil {
		return errors.New("Frame.FrameTail pack error\n" + err.Error())
	}

	return nil
}

func (this *Frame) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("Frame data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *Frame) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > FrameCurrentVersion {
		cutVer = FrameCurrentVersion
	}
	// check version
	if cutVer < FrameBaseVersion {
		errors.New("Frame cut version must large than FrameBaseVersion\n")
	}

	err = this.FrameHeader.UnpackFrom(cutVer, r)
	if err != nil {
		return errors.New("Frame.FrameHeader unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.CmdId)
	if err != nil {
		return errors.New("Frame.CmdId unpack error\n" + err.Error())
	}

	if this.Data == nil {
		this.Data = make([]byte, int(1024))
	}

	err = binary.Read(r, binary.BigEndian, this.Data[:])
	if err != nil {
		return errors.New("Frame.Data unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.FrameTail)
	if err != nil {
		return errors.New("Frame.FrameTail unpack error\n" + err.Error())
	}

	return err
}

// RoboMaster 机甲大师超级对抗赛
const GameTypeRoboMasterUC int64 = 1

// RoboMaster 机甲大师高校单项赛
const GameTypeRoboMasterCS int64 = 2

// ICRA RoboMaster 高校人工智能挑战赛
const GameTypeRoboMasterICRA int64 = 3

// RoboMaster 机甲大师高校联盟赛 3V3 对抗
const GameTypeRoboMasterUL int64 = 4

// RoboMaster 机甲大师高校联盟赛步兵对抗
const GameTypeRoboMasterULStandard int64 = 5

// 未开始比赛
const GameStageDefault int64 = 0

// 准备阶段
const GameStagePrepare int64 = 1

// 十五秒裁判系统自检阶段
const GameStageJudgeSystemCheck int64 = 2

// 五秒倒计时
const GameStageCountdown int64 = 3

// 比赛中
const GameStageRunning int64 = 4

// 比赛结算中
const GameStageEnd int64 = 5
const (
	GameStateDataBaseVersion    uint32 = 1
	GameStateDataCurrentVersion uint32 = 1
)

// GameStateData
type GameStateData struct {
	GameState byte `tdr_field:"game_state"`

	TimeRemaining uint16 `tdr_field:"time_remaining"`

	Timestamp uint64 `tdr_field:"timestamp"`
}

func NewGameStateData() *GameStateData {
	obj := new(GameStateData)
	obj.Init()
	return obj
}

func (this *GameStateData) GetBaseVersion() uint32 {
	return GameStateDataBaseVersion
}

func (this *GameStateData) GetCurrentVersion() uint32 {
	return GameStateDataCurrentVersion
}

func (this *GameStateData) Init() {

}

func (this *GameStateData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("GameStateData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *GameStateData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > GameStateDataCurrentVersion {
		cutVer = GameStateDataCurrentVersion
	}
	// check cut version
	if cutVer < GameStateDataBaseVersion {
		return errors.New("GameStateData cut version must large than GameStateDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.GameState)
	if err != nil {
		return errors.New("GameStateData.GameState pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.TimeRemaining)
	if err != nil {
		return errors.New("GameStateData.TimeRemaining pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Timestamp)
	if err != nil {
		return errors.New("GameStateData.Timestamp pack error\n" + err.Error())
	}

	return nil
}

func (this *GameStateData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("GameStateData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *GameStateData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > GameStateDataCurrentVersion {
		cutVer = GameStateDataCurrentVersion
	}
	// check version
	if cutVer < GameStateDataBaseVersion {
		errors.New("GameStateData cut version must large than GameStateDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.GameState)
	if err != nil {
		return errors.New("GameStateData.GameState unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.TimeRemaining)
	if err != nil {
		return errors.New("GameStateData.TimeRemaining unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Timestamp)
	if err != nil {
		return errors.New("GameStateData.Timestamp unpack error\n" + err.Error())
	}

	return err
}

// 平局
const GameResultDraw int64 = 0

// 红方胜利
const GameResultRedWin int64 = 1

// 蓝方胜利
const GameResultBlueWin int64 = 2
const (
	GameResultDataBaseVersion    uint32 = 1
	GameResultDataCurrentVersion uint32 = 1
)

// GameResultData
type GameResultData struct {
	GameResult byte `tdr_field:"game_result"`
}

func NewGameResultData() *GameResultData {
	obj := new(GameResultData)
	obj.Init()
	return obj
}

func (this *GameResultData) GetBaseVersion() uint32 {
	return GameResultDataBaseVersion
}

func (this *GameResultData) GetCurrentVersion() uint32 {
	return GameResultDataCurrentVersion
}

func (this *GameResultData) Init() {

}

func (this *GameResultData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("GameResultData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *GameResultData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > GameResultDataCurrentVersion {
		cutVer = GameResultDataCurrentVersion
	}
	// check cut version
	if cutVer < GameResultDataBaseVersion {
		return errors.New("GameResultData cut version must large than GameResultDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.GameResult)
	if err != nil {
		return errors.New("GameResultData.GameResult pack error\n" + err.Error())
	}

	return nil
}

func (this *GameResultData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("GameResultData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *GameResultData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > GameResultDataCurrentVersion {
		cutVer = GameResultDataCurrentVersion
	}
	// check version
	if cutVer < GameResultDataBaseVersion {
		errors.New("GameResultData cut version must large than GameResultDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.GameResult)
	if err != nil {
		return errors.New("GameResultData.GameResult unpack error\n" + err.Error())
	}

	return err
}

const (
	RobotHealthDataBaseVersion    uint32 = 1
	RobotHealthDataCurrentVersion uint32 = 1
)

// RobotHealthData
type RobotHealthData struct {
	RedHeroHealth uint16 `tdr_field:"Red1HeroHealth"`

	RedEngineerHealth uint16 `tdr_field:"Red2EngineerHealth"`

	RedStandardHealth uint16 `tdr_field:"Red3StandardHealth"`

	RedStandardHealth uint16 `tdr_field:"Red4StandardHealth"`

	RedPreserved uint16 `tdr_field:"Red5Preserved"`

	RedSentryHealth uint16 `tdr_field:"Red7SentryHealth"`

	RedOutpostHealth uint16 `tdr_field:"RedOutpostHealth"`

	RedBaseHealth uint16 `tdr_field:"RedBaseHealth"`

	BlueHeroHealth uint16 `tdr_field:"Blue1HeroHealth"`

	BlueEngineerHealth uint16 `tdr_field:"Blue2EngineerHealth"`

	BlueStandardHealth uint16 `tdr_field:"Blue3StandardHealth"`

	BlueStandardHealth uint16 `tdr_field:"Blue4StandardHealth"`

	BluePreserved uint16 `tdr_field:"Blue5Preserved"`

	BlueSentryHealth uint16 `tdr_field:"Blue7SentryHealth"`

	BlueOutpostHealth uint16 `tdr_field:"BlueOutpostHealth"`

	BlueBaseHealth uint16 `tdr_field:"BlueBaseHealth"`
}

func NewRobotHealthData() *RobotHealthData {
	obj := new(RobotHealthData)
	obj.Init()
	return obj
}

func (this *RobotHealthData) GetBaseVersion() uint32 {
	return RobotHealthDataBaseVersion
}

func (this *RobotHealthData) GetCurrentVersion() uint32 {
	return RobotHealthDataCurrentVersion
}

func (this *RobotHealthData) Init() {

}

func (this *RobotHealthData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("RobotHealthData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *RobotHealthData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > RobotHealthDataCurrentVersion {
		cutVer = RobotHealthDataCurrentVersion
	}
	// check cut version
	if cutVer < RobotHealthDataBaseVersion {
		return errors.New("RobotHealthData cut version must large than RobotHealthDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.RedHeroHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedHeroHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RedEngineerHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedEngineerHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RedStandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedStandardHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RedStandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedStandardHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RedPreserved)
	if err != nil {
		return errors.New("RobotHealthData.RedPreserved pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RedSentryHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedSentryHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RedOutpostHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedOutpostHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RedBaseHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedBaseHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BlueHeroHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueHeroHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BlueEngineerHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueEngineerHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BlueStandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueStandardHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BlueStandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueStandardHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BluePreserved)
	if err != nil {
		return errors.New("RobotHealthData.BluePreserved pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BlueSentryHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueSentryHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BlueOutpostHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueOutpostHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BlueBaseHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueBaseHealth pack error\n" + err.Error())
	}

	return nil
}

func (this *RobotHealthData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("RobotHealthData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *RobotHealthData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > RobotHealthDataCurrentVersion {
		cutVer = RobotHealthDataCurrentVersion
	}
	// check version
	if cutVer < RobotHealthDataBaseVersion {
		errors.New("RobotHealthData cut version must large than RobotHealthDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.RedHeroHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedHeroHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RedEngineerHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedEngineerHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RedStandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedStandardHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RedStandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedStandardHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RedPreserved)
	if err != nil {
		return errors.New("RobotHealthData.RedPreserved unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RedSentryHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedSentryHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RedOutpostHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedOutpostHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RedBaseHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedBaseHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BlueHeroHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueHeroHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BlueEngineerHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueEngineerHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BlueStandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueStandardHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BlueStandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueStandardHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BluePreserved)
	if err != nil {
		return errors.New("RobotHealthData.BluePreserved unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BlueSentryHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueSentryHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BlueOutpostHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueOutpostHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BlueBaseHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueBaseHealth unpack error\n" + err.Error())
	}

	return err
}
