// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.1
// source: client/client.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 传输鼠标键盘输入和自定义数据
// 自定义客户端→服务器
// 75Hz
type RemoteControl struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MouseX          int32                  `protobuf:"varint,1,opt,name=mouse_x,json=mouseX,proto3" json:"mouse_x,omitempty"`                              // 鼠标 x 轴移动速度，负值标识向左移动
	MouseY          int32                  `protobuf:"varint,2,opt,name=mouse_y,json=mouseY,proto3" json:"mouse_y,omitempty"`                              // 鼠标 y 轴移动速度，负值标识向下移动
	MouseZ          int32                  `protobuf:"varint,3,opt,name=mouse_z,json=mouseZ,proto3" json:"mouse_z,omitempty"`                              // 鼠标滚轮移动速度，负值标识向后滚动
	LeftButtonDown  bool                   `protobuf:"varint,4,opt,name=left_button_down,json=leftButtonDown,proto3" json:"left_button_down,omitempty"`    // 左键是否按下（false=抬起, true=按下）
	RightButtonDown bool                   `protobuf:"varint,5,opt,name=right_button_down,json=rightButtonDown,proto3" json:"right_button_down,omitempty"` // 右键是否按下（false=抬起, true=按下）
	KeyboardValue   uint32                 `protobuf:"varint,6,opt,name=keyboard_value,json=keyboardValue,proto3" json:"keyboard_value,omitempty"`         // 键盘按键位掩码
	MidButtonDown   bool                   `protobuf:"varint,7,opt,name=mid_button_down,json=midButtonDown,proto3" json:"mid_button_down,omitempty"`       // 中键是否按下（false=抬起, true=按下）
	Data            []byte                 `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`                                                 // 最大 30 字节的自定义数据
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RemoteControl) Reset() {
	*x = RemoteControl{}
	mi := &file_client_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoteControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoteControl) ProtoMessage() {}

func (x *RemoteControl) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoteControl.ProtoReflect.Descriptor instead.
func (*RemoteControl) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{0}
}

func (x *RemoteControl) GetMouseX() int32 {
	if x != nil {
		return x.MouseX
	}
	return 0
}

func (x *RemoteControl) GetMouseY() int32 {
	if x != nil {
		return x.MouseY
	}
	return 0
}

func (x *RemoteControl) GetMouseZ() int32 {
	if x != nil {
		return x.MouseZ
	}
	return 0
}

func (x *RemoteControl) GetLeftButtonDown() bool {
	if x != nil {
		return x.LeftButtonDown
	}
	return false
}

func (x *RemoteControl) GetRightButtonDown() bool {
	if x != nil {
		return x.RightButtonDown
	}
	return false
}

func (x *RemoteControl) GetKeyboardValue() uint32 {
	if x != nil {
		return x.KeyboardValue
	}
	return 0
}

func (x *RemoteControl) GetMidButtonDown() bool {
	if x != nil {
		return x.MidButtonDown
	}
	return false
}

func (x *RemoteControl) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 同步比赛全局状态信息
// 服务器→自定义客户端
// 5Hz
type GameStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CurrentRound      uint32                 `protobuf:"varint,1,opt,name=current_round,json=currentRound,proto3" json:"current_round,omitempty"`                  // 当前局号（从1开始）
	TotalRounds       uint32                 `protobuf:"varint,2,opt,name=total_rounds,json=totalRounds,proto3" json:"total_rounds,omitempty"`                     // 总局数
	RedScore          uint32                 `protobuf:"varint,3,opt,name=red_score,json=redScore,proto3" json:"red_score,omitempty"`                              // 红方得分
	BlueScore         uint32                 `protobuf:"varint,4,opt,name=blue_score,json=blueScore,proto3" json:"blue_score,omitempty"`                           // 蓝方得分
	CurrentStage      uint32                 `protobuf:"varint,5,opt,name=current_stage,json=currentStage,proto3" json:"current_stage,omitempty"`                  // 当前比赛阶段，枚举值：0=未开始比赛，1=准备阶段，2=十五秒裁判系统自检阶段，3=五秒倒计时，4=比赛中，5=比赛结算中
	StageCountdownSec int32                  `protobuf:"varint,6,opt,name=stage_countdown_sec,json=stageCountdownSec,proto3" json:"stage_countdown_sec,omitempty"` // 当前阶段剩余时间（单位：秒）
	StageElapsedSec   int32                  `protobuf:"varint,7,opt,name=stage_elapsed_sec,json=stageElapsedSec,proto3" json:"stage_elapsed_sec,omitempty"`       // 当前阶段已过时间（单位：秒）
	IsPaused          bool                   `protobuf:"varint,8,opt,name=is_paused,json=isPaused,proto3" json:"is_paused,omitempty"`                              // 比赛是否暂停（false=未暂停，true=暂停）
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GameStatus) Reset() {
	*x = GameStatus{}
	mi := &file_client_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStatus) ProtoMessage() {}

func (x *GameStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStatus.ProtoReflect.Descriptor instead.
func (*GameStatus) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{1}
}

func (x *GameStatus) GetCurrentRound() uint32 {
	if x != nil {
		return x.CurrentRound
	}
	return 0
}

func (x *GameStatus) GetTotalRounds() uint32 {
	if x != nil {
		return x.TotalRounds
	}
	return 0
}

func (x *GameStatus) GetRedScore() uint32 {
	if x != nil {
		return x.RedScore
	}
	return 0
}

func (x *GameStatus) GetBlueScore() uint32 {
	if x != nil {
		return x.BlueScore
	}
	return 0
}

func (x *GameStatus) GetCurrentStage() uint32 {
	if x != nil {
		return x.CurrentStage
	}
	return 0
}

func (x *GameStatus) GetStageCountdownSec() int32 {
	if x != nil {
		return x.StageCountdownSec
	}
	return 0
}

func (x *GameStatus) GetStageElapsedSec() int32 {
	if x != nil {
		return x.StageElapsedSec
	}
	return 0
}

func (x *GameStatus) GetIsPaused() bool {
	if x != nil {
		return x.IsPaused
	}
	return false
}

// 同步基地、前哨站和所有机器人状态
// 服务器→自定义客户端
// 1Hz
type GlobalUnitStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BaseHealth      uint32                 `protobuf:"varint,1,opt,name=base_health,json=baseHealth,proto3" json:"base_health,omitempty"`                  // 基地当前血量（0=已摧毁）
	BaseStatus      uint32                 `protobuf:"varint,2,opt,name=base_status,json=baseStatus,proto3" json:"base_status,omitempty"`                  // 基地状态，枚举值：0=无敌，1=解除无敌（护甲未展开），2=解除无敌（护甲展开）
	BaseShield      uint32                 `protobuf:"varint,3,opt,name=base_shield,json=baseShield,proto3" json:"base_shield,omitempty"`                  // 基地当前护盾值（0=无护盾）
	OutpostHealth   uint32                 `protobuf:"varint,4,opt,name=outpost_health,json=outpostHealth,proto3" json:"outpost_health,omitempty"`         // 前哨站当前血量（0=已摧毁）
	OutpostStatus   uint32                 `protobuf:"varint,5,opt,name=outpost_status,json=outpostStatus,proto3" json:"outpost_status,omitempty"`         // 前哨站状态，枚举值：0=无敌，1=存活（解除无敌，中部装甲旋转），2=存活（解除无敌，中部装甲停转），3=被击毁（不可重建），4=被击毁（可重建）
	RobotHealth     []uint32               `protobuf:"varint,6,rep,packed,name=robot_health,json=robotHealth,proto3" json:"robot_health,omitempty"`        // 所有机器人血量（先己方后对方，按机器人ID顺序排列）
	RobotBullets    []int32                `protobuf:"varint,7,rep,packed,name=robot_bullets,json=robotBullets,proto3" json:"robot_bullets,omitempty"`     // 己方机器人剩余累计发弹量（按机器人ID顺序排列）
	TotalDamageRed  uint32                 `protobuf:"varint,8,opt,name=total_damage_red,json=totalDamageRed,proto3" json:"total_damage_red,omitempty"`    // 红方累计总伤害
	TotalDamageBlue uint32                 `protobuf:"varint,9,opt,name=total_damage_blue,json=totalDamageBlue,proto3" json:"total_damage_blue,omitempty"` // 蓝方累计总伤害
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GlobalUnitStatus) Reset() {
	*x = GlobalUnitStatus{}
	mi := &file_client_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalUnitStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalUnitStatus) ProtoMessage() {}

func (x *GlobalUnitStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalUnitStatus.ProtoReflect.Descriptor instead.
func (*GlobalUnitStatus) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{2}
}

func (x *GlobalUnitStatus) GetBaseHealth() uint32 {
	if x != nil {
		return x.BaseHealth
	}
	return 0
}

func (x *GlobalUnitStatus) GetBaseStatus() uint32 {
	if x != nil {
		return x.BaseStatus
	}
	return 0
}

func (x *GlobalUnitStatus) GetBaseShield() uint32 {
	if x != nil {
		return x.BaseShield
	}
	return 0
}

func (x *GlobalUnitStatus) GetOutpostHealth() uint32 {
	if x != nil {
		return x.OutpostHealth
	}
	return 0
}

func (x *GlobalUnitStatus) GetOutpostStatus() uint32 {
	if x != nil {
		return x.OutpostStatus
	}
	return 0
}

func (x *GlobalUnitStatus) GetRobotHealth() []uint32 {
	if x != nil {
		return x.RobotHealth
	}
	return nil
}

func (x *GlobalUnitStatus) GetRobotBullets() []int32 {
	if x != nil {
		return x.RobotBullets
	}
	return nil
}

func (x *GlobalUnitStatus) GetTotalDamageRed() uint32 {
	if x != nil {
		return x.TotalDamageRed
	}
	return 0
}

func (x *GlobalUnitStatus) GetTotalDamageBlue() uint32 {
	if x != nil {
		return x.TotalDamageBlue
	}
	return 0
}

// 同步全局后勤信息
// 服务器→自定义客户端
// 1Hz
type GlobalLogisticsStatus struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RemainingEconomy     uint32                 `protobuf:"varint,1,opt,name=remaining_economy,json=remainingEconomy,proto3" json:"remaining_economy,omitempty"`               // 己方当前经济（剩余金币数）
	TotalEconomyObtained uint64                 `protobuf:"varint,2,opt,name=total_economy_obtained,json=totalEconomyObtained,proto3" json:"total_economy_obtained,omitempty"` // 己方累计总经济（比赛至今获得的总金币数）
	TechLevel            uint32                 `protobuf:"varint,3,opt,name=tech_level,json=techLevel,proto3" json:"tech_level,omitempty"`                                    // 己方科技等级（工程机器人曾装配的最高难度等级）
	EncryptionLevel      uint32                 `protobuf:"varint,4,opt,name=encryption_level,json=encryptionLevel,proto3" json:"encryption_level,omitempty"`                  // 己方加密等级（雷达解析信息波机制难度，1~3级）
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GlobalLogisticsStatus) Reset() {
	*x = GlobalLogisticsStatus{}
	mi := &file_client_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalLogisticsStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalLogisticsStatus) ProtoMessage() {}

func (x *GlobalLogisticsStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalLogisticsStatus.ProtoReflect.Descriptor instead.
func (*GlobalLogisticsStatus) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{3}
}

func (x *GlobalLogisticsStatus) GetRemainingEconomy() uint32 {
	if x != nil {
		return x.RemainingEconomy
	}
	return 0
}

func (x *GlobalLogisticsStatus) GetTotalEconomyObtained() uint64 {
	if x != nil {
		return x.TotalEconomyObtained
	}
	return 0
}

func (x *GlobalLogisticsStatus) GetTechLevel() uint32 {
	if x != nil {
		return x.TechLevel
	}
	return 0
}

func (x *GlobalLogisticsStatus) GetEncryptionLevel() uint32 {
	if x != nil {
		return x.EncryptionLevel
	}
	return 0
}

// 同步正在生效的全局特殊机制
// 服务器→自定义客户端
// 1Hz
type GlobalSpecialMechanism struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MechanismId      []uint32               `protobuf:"varint,1,rep,packed,name=mechanism_id,json=mechanismId,proto3" json:"mechanism_id,omitempty"`                  // 正在生效的机制ID列表，枚举值：1=己方堡垒被对方占领计时，2=对方堡垒被己方占领计时
	MechanismTimeSec []int32                `protobuf:"varint,2,rep,packed,name=mechanism_time_sec,json=mechanismTimeSec,proto3" json:"mechanism_time_sec,omitempty"` // 对应机制的剩余时间（单位：秒，与mechanism_id一一对应）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GlobalSpecialMechanism) Reset() {
	*x = GlobalSpecialMechanism{}
	mi := &file_client_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalSpecialMechanism) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalSpecialMechanism) ProtoMessage() {}

func (x *GlobalSpecialMechanism) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalSpecialMechanism.ProtoReflect.Descriptor instead.
func (*GlobalSpecialMechanism) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{4}
}

func (x *GlobalSpecialMechanism) GetMechanismId() []uint32 {
	if x != nil {
		return x.MechanismId
	}
	return nil
}

func (x *GlobalSpecialMechanism) GetMechanismTimeSec() []int32 {
	if x != nil {
		return x.MechanismTimeSec
	}
	return nil
}

// 全局事件通知
// 服务器→自定义客户端
// 触发式发送（事件发生时发送）
type Event struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId int32                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"` // 事件编号，枚举值：
	// 1=击杀事件（参数为“击杀者ID+被击毁机器人ID”拼接），2=基地/前哨站被摧毁事件（参数为被击毁目标ID），
	// 3=能量机关可激活次数变化（参数为变化后可激活次数），4=能量单元可进入激活状态（无参数），
	// 5=能量机关激活成功的灯臂数量与平均环数（参数为“激活臂数+平均环数”拼接），6=能量机关被激活（参数含激活类型），
	// 7=己方英雄进入部署模式（无参数），8=己方英雄造成狙击伤害（参数为累计伤害量），9=对方英雄造成狙击伤害（参数为累计伤害量），
	// 10=己方呼叫空中支援（无参数），11=己方空中支援被打断（参数为对方剩余可打断次数），12=对方呼叫空中支援（无参数），
	// 13=对方空中支援被打断（参数为己方剩余可打断次数），14=飞镖命中（参数为命中目标：1=前哨站，2=基地固定目标等），
	// 15=飞镖闸门开启（参数：1=己方开启，2=对方开启），16=己方基地遭到攻击（无参数，5秒内置冷却），
	// 17=前哨站停转（参数：1=己方前哨，2=对方前哨），18=基地护甲展开（参数：1=己方基地，2=对方基地）
	Param         string `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"` // 事件参数（含义随event_id变化，无参数时为空字符串）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_client_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetEventId() int32 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *Event) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

// 机器人一次存活期间累计受伤统计
// 服务器→自定义客户端
// 1Hz
type RobotInjuryStat struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalDamage           uint32                 `protobuf:"varint,1,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`                                 // 该次存活累计受伤总计（单位：血量）
	CollisionDamage       uint32                 `protobuf:"varint,2,opt,name=collision_damage,json=collisionDamage,proto3" json:"collision_damage,omitempty"`                     // 撞击伤害（单位：血量）
	SmallProjectileDamage uint32                 `protobuf:"varint,3,opt,name=small_projectile_damage,json=smallProjectileDamage,proto3" json:"small_projectile_damage,omitempty"` // 17mm弹丸伤害（单位：血量）
	LargeProjectileDamage uint32                 `protobuf:"varint,4,opt,name=large_projectile_damage,json=largeProjectileDamage,proto3" json:"large_projectile_damage,omitempty"` // 42mm弹丸伤害（单位：血量）
	DartSplashDamage      uint32                 `protobuf:"varint,5,opt,name=dart_splash_damage,json=dartSplashDamage,proto3" json:"dart_splash_damage,omitempty"`                // 飞镖溅射伤害（单位：血量）
	ModuleOfflineDamage   uint32                 `protobuf:"varint,6,opt,name=module_offline_damage,json=moduleOfflineDamage,proto3" json:"module_offline_damage,omitempty"`       // 模块离线扣血（单位：血量）
	WifiOfflineDamage     uint32                 `protobuf:"varint,7,opt,name=wifi_offline_damage,json=wifiOfflineDamage,proto3" json:"wifi_offline_damage,omitempty"`             // WiFi离线扣血（单位：血量）
	PenaltyDamage         uint32                 `protobuf:"varint,8,opt,name=penalty_damage,json=penaltyDamage,proto3" json:"penalty_damage,omitempty"`                           // 判罚扣血（单位：血量）
	ServerKillDamage      uint32                 `protobuf:"varint,9,opt,name=server_kill_damage,json=serverKillDamage,proto3" json:"server_kill_damage,omitempty"`                // 服务器强制战亡扣血（单位：血量）
	KillerId              uint32                 `protobuf:"varint,10,opt,name=killer_id,json=killerId,proto3" json:"killer_id,omitempty"`                                         // 击杀者ID（未检测到击杀者时为0，ID规则见附录二）
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RobotInjuryStat) Reset() {
	*x = RobotInjuryStat{}
	mi := &file_client_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotInjuryStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotInjuryStat) ProtoMessage() {}

func (x *RobotInjuryStat) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotInjuryStat.ProtoReflect.Descriptor instead.
func (*RobotInjuryStat) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{6}
}

func (x *RobotInjuryStat) GetTotalDamage() uint32 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetCollisionDamage() uint32 {
	if x != nil {
		return x.CollisionDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetSmallProjectileDamage() uint32 {
	if x != nil {
		return x.SmallProjectileDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetLargeProjectileDamage() uint32 {
	if x != nil {
		return x.LargeProjectileDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetDartSplashDamage() uint32 {
	if x != nil {
		return x.DartSplashDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetModuleOfflineDamage() uint32 {
	if x != nil {
		return x.ModuleOfflineDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetWifiOfflineDamage() uint32 {
	if x != nil {
		return x.WifiOfflineDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetPenaltyDamage() uint32 {
	if x != nil {
		return x.PenaltyDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetServerKillDamage() uint32 {
	if x != nil {
		return x.ServerKillDamage
	}
	return 0
}

func (x *RobotInjuryStat) GetKillerId() uint32 {
	if x != nil {
		return x.KillerId
	}
	return 0
}

// 机器人复活状态同步
// 服务器→自定义客户端
// 1Hz
type RobotRespawnStatus struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	IsPendingRespawn       bool                   `protobuf:"varint,1,opt,name=is_pending_respawn,json=isPendingRespawn,proto3" json:"is_pending_respawn,omitempty"`                   // 是否处于待复活状态（false=正常，true=待复活）
	TotalRespawnProgress   uint32                 `protobuf:"varint,2,opt,name=total_respawn_progress,json=totalRespawnProgress,proto3" json:"total_respawn_progress,omitempty"`       // 复活所需总读条（固定值，按赛事规则配置）
	CurrentRespawnProgress uint32                 `protobuf:"varint,3,opt,name=current_respawn_progress,json=currentRespawnProgress,proto3" json:"current_respawn_progress,omitempty"` // 当前复活读条进度（0~total_respawn_progress）
	CanFreeRespawn         bool                   `protobuf:"varint,4,opt,name=can_free_respawn,json=canFreeRespawn,proto3" json:"can_free_respawn,omitempty"`                         // 是否可以免费复活（false=不可，true=可）
	GoldCostForRespawn     uint32                 `protobuf:"varint,5,opt,name=gold_cost_for_respawn,json=goldCostForRespawn,proto3" json:"gold_cost_for_respawn,omitempty"`           // 花费金币复活所需金币数（免费复活时为0）
	CanPayForRespawn       bool                   `protobuf:"varint,6,opt,name=can_pay_for_respawn,json=canPayForRespawn,proto3" json:"can_pay_for_respawn,omitempty"`                 // 是否允许花费金币复活（false=不可，true=可）
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RobotRespawnStatus) Reset() {
	*x = RobotRespawnStatus{}
	mi := &file_client_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotRespawnStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotRespawnStatus) ProtoMessage() {}

func (x *RobotRespawnStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotRespawnStatus.ProtoReflect.Descriptor instead.
func (*RobotRespawnStatus) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{7}
}

func (x *RobotRespawnStatus) GetIsPendingRespawn() bool {
	if x != nil {
		return x.IsPendingRespawn
	}
	return false
}

func (x *RobotRespawnStatus) GetTotalRespawnProgress() uint32 {
	if x != nil {
		return x.TotalRespawnProgress
	}
	return 0
}

func (x *RobotRespawnStatus) GetCurrentRespawnProgress() uint32 {
	if x != nil {
		return x.CurrentRespawnProgress
	}
	return 0
}

func (x *RobotRespawnStatus) GetCanFreeRespawn() bool {
	if x != nil {
		return x.CanFreeRespawn
	}
	return false
}

func (x *RobotRespawnStatus) GetGoldCostForRespawn() uint32 {
	if x != nil {
		return x.GoldCostForRespawn
	}
	return 0
}

func (x *RobotRespawnStatus) GetCanPayForRespawn() bool {
	if x != nil {
		return x.CanPayForRespawn
	}
	return false
}

// 机器人固定属性和配置
// 服务器→自定义客户端
// 1Hz
type RobotStaticStatus struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ConnectionState          uint32                 `protobuf:"varint,1,opt,name=connection_state,json=connectionState,proto3" json:"connection_state,omitempty"`                              // 连接状态，枚举值：0=未连接，1=已连接
	FieldState               uint32                 `protobuf:"varint,2,opt,name=field_state,json=fieldState,proto3" json:"field_state,omitempty"`                                             // 上场状态，枚举值：0=已上场，1=未上场
	AliveState               uint32                 `protobuf:"varint,3,opt,name=alive_state,json=aliveState,proto3" json:"alive_state,omitempty"`                                             // 存活状态，枚举值：0=未知，1=存活，2=战亡
	RobotId                  uint32                 `protobuf:"varint,4,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`                                                      // 机器人编号（ID规则见附录二，如1=红方英雄，101=蓝方英雄）
	RobotType                uint32                 `protobuf:"varint,5,opt,name=robot_type,json=robotType,proto3" json:"robot_type,omitempty"`                                                // 机器人类型，枚举值：1=英雄，2=工程，3=步兵，4=哨兵，5=空中，6=飞镖，7=雷达
	PerformanceSystemShooter uint32                 `protobuf:"varint,6,opt,name=performance_system_shooter,json=performanceSystemShooter,proto3" json:"performance_system_shooter,omitempty"` // 性能体系-发射机构，枚举值：1=冷却优先，2=爆发优先，3=英雄近战优先，4=英雄远程优先
	PerformanceSystemChassis uint32                 `protobuf:"varint,7,opt,name=performance_system_chassis,json=performanceSystemChassis,proto3" json:"performance_system_chassis,omitempty"` // 性能体系-底盘，枚举值：1=血量优先，2=功率优先，3=英雄近战优先，4=英雄远程优先
	Level                    uint32                 `protobuf:"varint,8,opt,name=level,proto3" json:"level,omitempty"`                                                                         // 当前等级（1~max_level，按赛事规则配置）
	MaxHealth                uint32                 `protobuf:"varint,9,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`                                                // 最大血量（按等级和性能体系配置）
	MaxHeat                  uint32                 `protobuf:"varint,10,opt,name=max_heat,json=maxHeat,proto3" json:"max_heat,omitempty"`                                                     // 最大射击热量（发射机构的热量上限）
	HeatCooldownRate         float32                `protobuf:"fixed32,11,opt,name=heat_cooldown_rate,json=heatCooldownRate,proto3" json:"heat_cooldown_rate,omitempty"`                       // 热量冷却速率（单位：热量/秒）
	MaxPower                 uint32                 `protobuf:"varint,12,opt,name=max_power,json=maxPower,proto3" json:"max_power,omitempty"`                                                  // 最大功率（底盘功率上限，单位：W）
	MaxBufferEnergy          uint32                 `protobuf:"varint,13,opt,name=max_buffer_energy,json=maxBufferEnergy,proto3" json:"max_buffer_energy,omitempty"`                           // 最大缓冲能量（单位：J）
	MaxChassisEnergy         uint32                 `protobuf:"varint,14,opt,name=max_chassis_energy,json=maxChassisEnergy,proto3" json:"max_chassis_energy,omitempty"`                        // 最大底盘能量（单位：J）
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RobotStaticStatus) Reset() {
	*x = RobotStaticStatus{}
	mi := &file_client_client_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotStaticStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotStaticStatus) ProtoMessage() {}

func (x *RobotStaticStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotStaticStatus.ProtoReflect.Descriptor instead.
func (*RobotStaticStatus) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{8}
}

func (x *RobotStaticStatus) GetConnectionState() uint32 {
	if x != nil {
		return x.ConnectionState
	}
	return 0
}

func (x *RobotStaticStatus) GetFieldState() uint32 {
	if x != nil {
		return x.FieldState
	}
	return 0
}

func (x *RobotStaticStatus) GetAliveState() uint32 {
	if x != nil {
		return x.AliveState
	}
	return 0
}

func (x *RobotStaticStatus) GetRobotId() uint32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *RobotStaticStatus) GetRobotType() uint32 {
	if x != nil {
		return x.RobotType
	}
	return 0
}

func (x *RobotStaticStatus) GetPerformanceSystemShooter() uint32 {
	if x != nil {
		return x.PerformanceSystemShooter
	}
	return 0
}

func (x *RobotStaticStatus) GetPerformanceSystemChassis() uint32 {
	if x != nil {
		return x.PerformanceSystemChassis
	}
	return 0
}

func (x *RobotStaticStatus) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxHealth() uint32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxHeat() uint32 {
	if x != nil {
		return x.MaxHeat
	}
	return 0
}

func (x *RobotStaticStatus) GetHeatCooldownRate() float32 {
	if x != nil {
		return x.HeatCooldownRate
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxPower() uint32 {
	if x != nil {
		return x.MaxPower
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxBufferEnergy() uint32 {
	if x != nil {
		return x.MaxBufferEnergy
	}
	return 0
}

func (x *RobotStaticStatus) GetMaxChassisEnergy() uint32 {
	if x != nil {
		return x.MaxChassisEnergy
	}
	return 0
}

// 机器人实时数据
// 服务器→自定义客户端
// 10Hz
type RobotDynamicStatus struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	CurrentHealth          uint32                 `protobuf:"varint,1,opt,name=current_health,json=currentHealth,proto3" json:"current_health,omitempty"`                                 // 当前血量（0~max_health）
	CurrentHeat            float32                `protobuf:"fixed32,2,opt,name=current_heat,json=currentHeat,proto3" json:"current_heat,omitempty"`                                      // 当前射击热量（0~max_heat）
	LastProjectileFireRate float32                `protobuf:"fixed32,3,opt,name=last_projectile_fire_rate,json=lastProjectileFireRate,proto3" json:"last_projectile_fire_rate,omitempty"` // 上一次弹丸射速（单位：Hz）
	CurrentChassisEnergy   uint32                 `protobuf:"varint,4,opt,name=current_chassis_energy,json=currentChassisEnergy,proto3" json:"current_chassis_energy,omitempty"`          // 当前剩余底盘能量（0~max_chassis_energy，单位：J）
	CurrentBufferEnergy    uint32                 `protobuf:"varint,5,opt,name=current_buffer_energy,json=currentBufferEnergy,proto3" json:"current_buffer_energy,omitempty"`             // 当前缓冲能量（0~max_buffer_energy，单位：J）
	CurrentExperience      uint32                 `protobuf:"varint,6,opt,name=current_experience,json=currentExperience,proto3" json:"current_experience,omitempty"`                     // 当前经验值（0~experience_for_upgrade）
	ExperienceForUpgrade   uint32                 `protobuf:"varint,7,opt,name=experience_for_upgrade,json=experienceForUpgrade,proto3" json:"experience_for_upgrade,omitempty"`          // 升级所需经验值（升级后更新）
	TotalProjectilesFired  uint32                 `protobuf:"varint,8,opt,name=total_projectiles_fired,json=totalProjectilesFired,proto3" json:"total_projectiles_fired,omitempty"`       // 累计已发弹量（比赛至今总发射数）
	RemainingAmmo          uint32                 `protobuf:"varint,9,opt,name=remaining_ammo,json=remainingAmmo,proto3" json:"remaining_ammo,omitempty"`                                 // 剩余允许发弹量（当前可发射的弹丸数）
	IsOutOfCombat          bool                   `protobuf:"varint,10,opt,name=is_out_of_combat,json=isOutOfCombat,proto3" json:"is_out_of_combat,omitempty"`                            // 是否处于脱战状态（false=战斗中，true=脱战）
	OutOfCombatCountdown   uint32                 `protobuf:"varint,11,opt,name=out_of_combat_countdown,json=outOfCombatCountdown,proto3" json:"out_of_combat_countdown,omitempty"`       // 脱战状态倒计时（单位：秒，脱战时递减，非脱战时为0）
	CanRemoteHeal          bool                   `protobuf:"varint,12,opt,name=can_remote_heal,json=canRemoteHeal,proto3" json:"can_remote_heal,omitempty"`                              // 是否可以远程补血（false=不可，true=可）
	CanRemoteAmmo          bool                   `protobuf:"varint,13,opt,name=can_remote_ammo,json=canRemoteAmmo,proto3" json:"can_remote_ammo,omitempty"`                              // 是否可以远程补弹（false=不可，true=可）
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RobotDynamicStatus) Reset() {
	*x = RobotDynamicStatus{}
	mi := &file_client_client_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotDynamicStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotDynamicStatus) ProtoMessage() {}

func (x *RobotDynamicStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotDynamicStatus.ProtoReflect.Descriptor instead.
func (*RobotDynamicStatus) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{9}
}

func (x *RobotDynamicStatus) GetCurrentHealth() uint32 {
	if x != nil {
		return x.CurrentHealth
	}
	return 0
}

func (x *RobotDynamicStatus) GetCurrentHeat() float32 {
	if x != nil {
		return x.CurrentHeat
	}
	return 0
}

func (x *RobotDynamicStatus) GetLastProjectileFireRate() float32 {
	if x != nil {
		return x.LastProjectileFireRate
	}
	return 0
}

func (x *RobotDynamicStatus) GetCurrentChassisEnergy() uint32 {
	if x != nil {
		return x.CurrentChassisEnergy
	}
	return 0
}

func (x *RobotDynamicStatus) GetCurrentBufferEnergy() uint32 {
	if x != nil {
		return x.CurrentBufferEnergy
	}
	return 0
}

func (x *RobotDynamicStatus) GetCurrentExperience() uint32 {
	if x != nil {
		return x.CurrentExperience
	}
	return 0
}

func (x *RobotDynamicStatus) GetExperienceForUpgrade() uint32 {
	if x != nil {
		return x.ExperienceForUpgrade
	}
	return 0
}

func (x *RobotDynamicStatus) GetTotalProjectilesFired() uint32 {
	if x != nil {
		return x.TotalProjectilesFired
	}
	return 0
}

func (x *RobotDynamicStatus) GetRemainingAmmo() uint32 {
	if x != nil {
		return x.RemainingAmmo
	}
	return 0
}

func (x *RobotDynamicStatus) GetIsOutOfCombat() bool {
	if x != nil {
		return x.IsOutOfCombat
	}
	return false
}

func (x *RobotDynamicStatus) GetOutOfCombatCountdown() uint32 {
	if x != nil {
		return x.OutOfCombatCountdown
	}
	return 0
}

func (x *RobotDynamicStatus) GetCanRemoteHeal() bool {
	if x != nil {
		return x.CanRemoteHeal
	}
	return false
}

func (x *RobotDynamicStatus) GetCanRemoteAmmo() bool {
	if x != nil {
		return x.CanRemoteAmmo
	}
	return false
}

// 机器人各模块运行状态
// 服务器→自定义客户端
// 1Hz
type RobotModuleStatus struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PowerManager      uint32                 `protobuf:"varint,1,opt,name=power_manager,json=powerManager,proto3" json:"power_manager,omitempty"`                // 电源管理模块状态，枚举值：0=离线，1=在线
	Rfid              uint32                 `protobuf:"varint,2,opt,name=rfid,proto3" json:"rfid,omitempty"`                                                    // RFID模块状态，枚举值：0=离线，1=在线
	LightStrip        uint32                 `protobuf:"varint,3,opt,name=light_strip,json=lightStrip,proto3" json:"light_strip,omitempty"`                      // 灯条模块状态，枚举值：0=离线，1=在线
	SmallShooter      uint32                 `protobuf:"varint,4,opt,name=small_shooter,json=smallShooter,proto3" json:"small_shooter,omitempty"`                // 17mm发射机构状态，枚举值：0=离线，1=在线
	BigShooter        uint32                 `protobuf:"varint,5,opt,name=big_shooter,json=bigShooter,proto3" json:"big_shooter,omitempty"`                      // 42mm发射机构状态，枚举值：0=离线，1=在线
	Uwb               uint32                 `protobuf:"varint,6,opt,name=uwb,proto3" json:"uwb,omitempty"`                                                      // 定位模块（UWB）状态，枚举值：0=离线，1=在线
	Armor             uint32                 `protobuf:"varint,7,opt,name=armor,proto3" json:"armor,omitempty"`                                                  // 装甲模块状态，枚举值：0=离线，1=在线
	VideoTransmission uint32                 `protobuf:"varint,8,opt,name=video_transmission,json=videoTransmission,proto3" json:"video_transmission,omitempty"` // 图传模块状态，枚举值：0=离线，1=在线
	Capacitor         uint32                 `protobuf:"varint,9,opt,name=capacitor,proto3" json:"capacitor,omitempty"`                                          // 电容模块状态，枚举值：0=离线，1=在线
	MainController    uint32                 `protobuf:"varint,10,opt,name=main_controller,json=mainController,proto3" json:"main_controller,omitempty"`         // 主控模块状态，枚举值：0=离线，1=在线
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RobotModuleStatus) Reset() {
	*x = RobotModuleStatus{}
	mi := &file_client_client_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotModuleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotModuleStatus) ProtoMessage() {}

func (x *RobotModuleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotModuleStatus.ProtoReflect.Descriptor instead.
func (*RobotModuleStatus) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{10}
}

func (x *RobotModuleStatus) GetPowerManager() uint32 {
	if x != nil {
		return x.PowerManager
	}
	return 0
}

func (x *RobotModuleStatus) GetRfid() uint32 {
	if x != nil {
		return x.Rfid
	}
	return 0
}

func (x *RobotModuleStatus) GetLightStrip() uint32 {
	if x != nil {
		return x.LightStrip
	}
	return 0
}

func (x *RobotModuleStatus) GetSmallShooter() uint32 {
	if x != nil {
		return x.SmallShooter
	}
	return 0
}

func (x *RobotModuleStatus) GetBigShooter() uint32 {
	if x != nil {
		return x.BigShooter
	}
	return 0
}

func (x *RobotModuleStatus) GetUwb() uint32 {
	if x != nil {
		return x.Uwb
	}
	return 0
}

func (x *RobotModuleStatus) GetArmor() uint32 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *RobotModuleStatus) GetVideoTransmission() uint32 {
	if x != nil {
		return x.VideoTransmission
	}
	return 0
}

func (x *RobotModuleStatus) GetCapacitor() uint32 {
	if x != nil {
		return x.Capacitor
	}
	return 0
}

func (x *RobotModuleStatus) GetMainController() uint32 {
	if x != nil {
		return x.MainController
	}
	return 0
}

// 机器人空间坐标和朝向
// 服务器→自定义客户端
// 1Hz
type RobotPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`     // 世界坐标X轴（单位：m，场地坐标规则见文档1.3.2）
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`     // 世界坐标Y轴（单位：m）
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`     // 世界坐标Z轴（单位：m，地面为0，向上为正）
	Yaw           float32                `protobuf:"fixed32,4,opt,name=yaw,proto3" json:"yaw,omitempty"` // 测速模块朝向（单位：度，正北为0度，顺时针递增）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotPosition) Reset() {
	*x = RobotPosition{}
	mi := &file_client_client_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPosition) ProtoMessage() {}

func (x *RobotPosition) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPosition.ProtoReflect.Descriptor instead.
func (*RobotPosition) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{11}
}

func (x *RobotPosition) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RobotPosition) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RobotPosition) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *RobotPosition) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

// Buff效果信息
// 服务器→自定义客户端
// 获得增益时触发发送，此后1Hz定频发送直到失去增益
type Buff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RobotId       uint32                 `protobuf:"varint,1,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`                  // 享有Buff的机器人ID（ID规则见附录二）
	BuffType      uint32                 `protobuf:"varint,2,opt,name=buff_type,json=buffType,proto3" json:"buff_type,omitempty"`               // Buff类型，枚举值：1=攻击增益，2=防御增益，3=射击热量冷却增益，4=底盘功率增益，5=回血增益，6=可兑换允许发弹量，7=地形跨越增益（预备）
	BuffLevel     int32                  `protobuf:"varint,3,opt,name=buff_level,json=buffLevel,proto3" json:"buff_level,omitempty"`            // Buff增益值（百分比或固定值，随buff_type变化：如攻击增益为50表示50%攻击提升）
	BuffMaxTime   uint32                 `protobuf:"varint,4,opt,name=buff_max_time,json=buffMaxTime,proto3" json:"buff_max_time,omitempty"`    // Buff最大持续时间（单位：秒，初始配置值）
	BuffLeftTime  uint32                 `protobuf:"varint,5,opt,name=buff_left_time,json=buffLeftTime,proto3" json:"buff_left_time,omitempty"` // Buff剩余时间（单位：秒，递减至0时Buff失效）
	MsgParams     string                 `protobuf:"bytes,6,opt,name=msg_params,json=msgParams,proto3" json:"msg_params,omitempty"`             // 额外文字参数（如Buff生效说明，无额外信息时为空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buff) Reset() {
	*x = Buff{}
	mi := &file_client_client_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buff) ProtoMessage() {}

func (x *Buff) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buff.ProtoReflect.Descriptor instead.
func (*Buff) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{12}
}

func (x *Buff) GetRobotId() uint32 {
	if x != nil {
		return x.RobotId
	}
	return 0
}

func (x *Buff) GetBuffType() uint32 {
	if x != nil {
		return x.BuffType
	}
	return 0
}

func (x *Buff) GetBuffLevel() int32 {
	if x != nil {
		return x.BuffLevel
	}
	return 0
}

func (x *Buff) GetBuffMaxTime() uint32 {
	if x != nil {
		return x.BuffMaxTime
	}
	return 0
}

func (x *Buff) GetBuffLeftTime() uint32 {
	if x != nil {
		return x.BuffLeftTime
	}
	return 0
}

func (x *Buff) GetMsgParams() string {
	if x != nil {
		return x.MsgParams
	}
	return ""
}

// 判罚信息同步
// 服务器→自定义客户端
// 触发式发送（判罚发生时发送）
type PenaltyInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PenaltyType      uint32                 `protobuf:"varint,1,opt,name=penalty_type,json=penaltyType,proto3" json:"penalty_type,omitempty"`                  // 受罚类型，枚举值：1=黄牌，2=双方黄牌，3=红牌，4=超功率，5=超热量，6=超射速
	PenaltyEffectSec uint32                 `protobuf:"varint,2,opt,name=penalty_effect_sec,json=penaltyEffectSec,proto3" json:"penalty_effect_sec,omitempty"` // 受罚效果时长（单位：秒，如黄牌禁赛时间）
	TotalPenaltyNum  uint32                 `protobuf:"varint,3,opt,name=total_penalty_num,json=totalPenaltyNum,proto3" json:"total_penalty_num,omitempty"`    // 当前判罚数量（该场次累计判罚次数）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PenaltyInfo) Reset() {
	*x = PenaltyInfo{}
	mi := &file_client_client_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PenaltyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PenaltyInfo) ProtoMessage() {}

func (x *PenaltyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PenaltyInfo.ProtoReflect.Descriptor instead.
func (*PenaltyInfo) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{13}
}

func (x *PenaltyInfo) GetPenaltyType() uint32 {
	if x != nil {
		return x.PenaltyType
	}
	return 0
}

func (x *PenaltyInfo) GetPenaltyEffectSec() uint32 {
	if x != nil {
		return x.PenaltyEffectSec
	}
	return 0
}

func (x *PenaltyInfo) GetTotalPenaltyNum() uint32 {
	if x != nil {
		return x.TotalPenaltyNum
	}
	return 0
}

// 哨兵轨迹规划信息
// 服务器→自定义客户端
// 1Hz
type RobotPathPlanInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Intention     uint32                 `protobuf:"varint,1,opt,name=intention,proto3" json:"intention,omitempty"`                    // 哨兵意图，枚举值：1=攻击，2=防守，3=移动
	StartPosX     uint32                 `protobuf:"varint,2,opt,name=start_pos_x,json=startPosX,proto3" json:"start_pos_x,omitempty"` // 起始点X坐标（单位：dm，分米，小地图坐标规则见文档1.3.2）
	StartPosY     uint32                 `protobuf:"varint,3,opt,name=start_pos_y,json=startPosY,proto3" json:"start_pos_y,omitempty"` // 起始点Y坐标（单位：dm）
	OffsetX       []int32                `protobuf:"varint,4,rep,packed,name=offset_x,json=offsetX,proto3" json:"offset_x,omitempty"`  // 相对起始点X增量数组（共49个值，范围-128~+127，单位：dm，与offset_y一一对应组成路径点）
	OffsetY       []int32                `protobuf:"varint,5,rep,packed,name=offset_y,json=offsetY,proto3" json:"offset_y,omitempty"`  // 相对起始点Y增量数组（共49个值，范围-128~+127，单位：dm）
	SenderId      uint32                 `protobuf:"varint,6,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`      // 发送者ID（哨兵机器人ID，如7=红方哨兵，107=蓝方哨兵）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotPathPlanInfo) Reset() {
	*x = RobotPathPlanInfo{}
	mi := &file_client_client_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotPathPlanInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPathPlanInfo) ProtoMessage() {}

func (x *RobotPathPlanInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPathPlanInfo.ProtoReflect.Descriptor instead.
func (*RobotPathPlanInfo) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{14}
}

func (x *RobotPathPlanInfo) GetIntention() uint32 {
	if x != nil {
		return x.Intention
	}
	return 0
}

func (x *RobotPathPlanInfo) GetStartPosX() uint32 {
	if x != nil {
		return x.StartPosX
	}
	return 0
}

func (x *RobotPathPlanInfo) GetStartPosY() uint32 {
	if x != nil {
		return x.StartPosY
	}
	return 0
}

func (x *RobotPathPlanInfo) GetOffsetX() []int32 {
	if x != nil {
		return x.OffsetX
	}
	return nil
}

func (x *RobotPathPlanInfo) GetOffsetY() []int32 {
	if x != nil {
		return x.OffsetY
	}
	return nil
}

func (x *RobotPathPlanInfo) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

// 云台手地图点击标记
// 自定义客户端→服务器
// 触发式发送（点击地图时发送）
type MapClickInfoNotify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsSendAll     uint32                 `protobuf:"varint,1,opt,name=is_send_all,json=isSendAll,proto3" json:"is_send_all,omitempty"` // 发送范围，枚举值：0=指定客户端，1=除哨兵外所有己方机器人，2=包含哨兵的所有己方机器人
	RobotId       []byte                 `protobuf:"bytes,2,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`          // 目标机器人ID列表（固定7字节，按ID顺序填充，未使用位填0；如红方发送给英雄+工程填[1,2,0,0,0,0,0]，蓝方填[101,102,0,0,0,0,0]）
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`                              // 标记类型，枚举值：1=攻击，2=防御，3=警戒，4=自定义
	EnemyId       uint32                 `protobuf:"varint,4,opt,name=enemy_id,json=enemyId,proto3" json:"enemy_id,omitempty"`         // 标定的对方ID（无标定目标时为0，ID规则见附录二）
	Ascii         uint32                 `protobuf:"varint,5,opt,name=ascii,proto3" json:"ascii,omitempty"`                            // 自定义图标ASCII码（mode=4时生效，如65=字母A，无自定义时为0）
	Type          uint32                 `protobuf:"varint,6,opt,name=type,proto3" json:"type,omitempty"`                              // 标记模式，枚举值：1=地图坐标标记，2=对方机器人标记
	ScreenX       uint32                 `protobuf:"varint,7,opt,name=screen_x,json=screenX,proto3" json:"screen_x,omitempty"`         // 屏幕坐标X（单位：像素，分辨率1920×1080，左上角为(0,0)）
	ScreenY       uint32                 `protobuf:"varint,8,opt,name=screen_y,json=screenY,proto3" json:"screen_y,omitempty"`         // 屏幕坐标Y（单位：像素）
	MapX          float32                `protobuf:"fixed32,9,opt,name=map_x,json=mapX,proto3" json:"map_x,omitempty"`                 // 地图坐标X（单位：m，type=1时生效，场地坐标规则见文档1.3.2）
	MapY          float32                `protobuf:"fixed32,10,opt,name=map_y,json=mapY,proto3" json:"map_y,omitempty"`                // 地图坐标Y（单位：m，type=1时生效）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapClickInfoNotify) Reset() {
	*x = MapClickInfoNotify{}
	mi := &file_client_client_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapClickInfoNotify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapClickInfoNotify) ProtoMessage() {}

func (x *MapClickInfoNotify) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapClickInfoNotify.ProtoReflect.Descriptor instead.
func (*MapClickInfoNotify) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{15}
}

func (x *MapClickInfoNotify) GetIsSendAll() uint32 {
	if x != nil {
		return x.IsSendAll
	}
	return 0
}

func (x *MapClickInfoNotify) GetRobotId() []byte {
	if x != nil {
		return x.RobotId
	}
	return nil
}

func (x *MapClickInfoNotify) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *MapClickInfoNotify) GetEnemyId() uint32 {
	if x != nil {
		return x.EnemyId
	}
	return 0
}

func (x *MapClickInfoNotify) GetAscii() uint32 {
	if x != nil {
		return x.Ascii
	}
	return 0
}

func (x *MapClickInfoNotify) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *MapClickInfoNotify) GetScreenX() uint32 {
	if x != nil {
		return x.ScreenX
	}
	return 0
}

func (x *MapClickInfoNotify) GetScreenY() uint32 {
	if x != nil {
		return x.ScreenY
	}
	return 0
}

func (x *MapClickInfoNotify) GetMapX() float32 {
	if x != nil {
		return x.MapX
	}
	return 0
}

func (x *MapClickInfoNotify) GetMapY() float32 {
	if x != nil {
		return x.MapY
	}
	return 0
}

// 雷达发送的机器人位置信息
// 服务器→自定义客户端
// 1Hz
type RaderInfoToClient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetRobotId uint32                 `protobuf:"varint,1,opt,name=target_robot_id,json=targetRobotId,proto3" json:"target_robot_id,omitempty"` // 目标机器人ID（对方机器人ID，规则见附录二）
	TargetPosX    float32                `protobuf:"fixed32,2,opt,name=target_pos_x,json=targetPosX,proto3" json:"target_pos_x,omitempty"`         // 目标位置X（单位：m，场地坐标规则见文档1.3.2）
	TargetPosY    float32                `protobuf:"fixed32,3,opt,name=target_pos_y,json=targetPosY,proto3" json:"target_pos_y,omitempty"`         // 目标位置Y（单位：m）
	TorwardAngle  float32                `protobuf:"fixed32,4,opt,name=torward_angle,json=torwardAngle,proto3" json:"torward_angle,omitempty"`     // 目标朝向角度（单位：度，正北为0度，顺时针递增）
	IsHighLight   uint32                 `protobuf:"varint,5,opt,name=is_high_light,json=isHighLight,proto3" json:"is_high_light,omitempty"`       // 是否特殊标识，枚举值：0=否，1=是（如对方机器人处于易伤状态）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RaderInfoToClient) Reset() {
	*x = RaderInfoToClient{}
	mi := &file_client_client_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RaderInfoToClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RaderInfoToClient) ProtoMessage() {}

func (x *RaderInfoToClient) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RaderInfoToClient.ProtoReflect.Descriptor instead.
func (*RaderInfoToClient) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{16}
}

func (x *RaderInfoToClient) GetTargetRobotId() uint32 {
	if x != nil {
		return x.TargetRobotId
	}
	return 0
}

func (x *RaderInfoToClient) GetTargetPosX() float32 {
	if x != nil {
		return x.TargetPosX
	}
	return 0
}

func (x *RaderInfoToClient) GetTargetPosY() float32 {
	if x != nil {
		return x.TargetPosY
	}
	return 0
}

func (x *RaderInfoToClient) GetTorwardAngle() float32 {
	if x != nil {
		return x.TorwardAngle
	}
	return 0
}

func (x *RaderInfoToClient) GetIsHighLight() uint32 {
	if x != nil {
		return x.IsHighLight
	}
	return 0
}

// 机器人自定义上传数据流（机器人端对应0x0310）
// 机器人→图传链路→自定义客户端
// 50Hz
type CustomByteBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 自定义数据包（最大1.2kbit，内容由用户自定义，如传感器原始数据、调试信息等）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CustomByteBlock) Reset() {
	*x = CustomByteBlock{}
	mi := &file_client_client_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomByteBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomByteBlock) ProtoMessage() {}

func (x *CustomByteBlock) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomByteBlock.ProtoReflect.Descriptor instead.
func (*CustomByteBlock) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{17}
}

func (x *CustomByteBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// 工程装配指令
// 自定义客户端→服务器
// 1Hz
type AssemblyCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     uint32                 `protobuf:"varint,1,opt,name=operation,proto3" json:"operation,omitempty"`   // 装配操作类型，枚举值：1=确认装配，2=取消装配
	Difficulty    uint32                 `protobuf:"varint,2,opt,name=difficulty,proto3" json:"difficulty,omitempty"` // 选中的装配难度（1~max_difficulty，按赛事规则配置，如1=简单，2=中等，3=困难）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssemblyCommand) Reset() {
	*x = AssemblyCommand{}
	mi := &file_client_client_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssemblyCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssemblyCommand) ProtoMessage() {}

func (x *AssemblyCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssemblyCommand.ProtoReflect.Descriptor instead.
func (*AssemblyCommand) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{18}
}

func (x *AssemblyCommand) GetOperation() uint32 {
	if x != nil {
		return x.Operation
	}
	return 0
}

func (x *AssemblyCommand) GetDifficulty() uint32 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

// 科技核心运动状态同步
// 服务器→自定义客户端
// 1Hz
type TechCoreMotionStateSync struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MaximumDifficultyLevel uint32                 `protobuf:"varint,1,opt,name=maximum_difficulty_level,json=maximumDifficultyLevel,proto3" json:"maximum_difficulty_level,omitempty"` // 当前可选择的最高装配难度等级（1~max_difficulty）
	Status                 uint32                 `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`                                                                 // 科技核心状态，枚举值：1=未进入装配状态，2=已选难度（科技核心移动中），3=移动完成（可进行首个装配步骤），4=上一步完成（可进行下一步），5=所有步骤完成，6=已确认装配（科技核心移动中）
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TechCoreMotionStateSync) Reset() {
	*x = TechCoreMotionStateSync{}
	mi := &file_client_client_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TechCoreMotionStateSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TechCoreMotionStateSync) ProtoMessage() {}

func (x *TechCoreMotionStateSync) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TechCoreMotionStateSync.ProtoReflect.Descriptor instead.
func (*TechCoreMotionStateSync) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{19}
}

func (x *TechCoreMotionStateSync) GetMaximumDifficultyLevel() uint32 {
	if x != nil {
		return x.MaximumDifficultyLevel
	}
	return 0
}

func (x *TechCoreMotionStateSync) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 步兵/英雄选择性能体系
// 自定义客户端→服务器
// 1Hz
type RobotPerformanceSelectionCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shooter       uint32                 `protobuf:"varint,1,opt,name=shooter,proto3" json:"shooter,omitempty"` // 发射机构性能体系，枚举值：1=冷却优先，2=爆发优先，3=英雄近战优先，4=英雄远程优先
	Chassis       uint32                 `protobuf:"varint,2,opt,name=chassis,proto3" json:"chassis,omitempty"` // 底盘性能体系，枚举值：1=血量优先，2=功率优先，3=英雄近战优先，4=英雄远程优先
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotPerformanceSelectionCommand) Reset() {
	*x = RobotPerformanceSelectionCommand{}
	mi := &file_client_client_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotPerformanceSelectionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPerformanceSelectionCommand) ProtoMessage() {}

func (x *RobotPerformanceSelectionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPerformanceSelectionCommand.ProtoReflect.Descriptor instead.
func (*RobotPerformanceSelectionCommand) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{20}
}

func (x *RobotPerformanceSelectionCommand) GetShooter() uint32 {
	if x != nil {
		return x.Shooter
	}
	return 0
}

func (x *RobotPerformanceSelectionCommand) GetChassis() uint32 {
	if x != nil {
		return x.Chassis
	}
	return 0
}

// 步兵/英雄机器人性能体系状态同步
// 服务器→自定义客户端
// 1Hz
type RobotPerformanceSelectionSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Shooter       uint32                 `protobuf:"varint,1,opt,name=shooter,proto3" json:"shooter,omitempty"` // 当前生效的发射机构性能体系（枚举值同RobotPerformanceSelectionCommand.shooter）
	Chassis       uint32                 `protobuf:"varint,2,opt,name=chassis,proto3" json:"chassis,omitempty"` // 当前生效的底盘性能体系（枚举值同RobotPerformanceSelectionCommand.chassis）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotPerformanceSelectionSync) Reset() {
	*x = RobotPerformanceSelectionSync{}
	mi := &file_client_client_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotPerformanceSelectionSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotPerformanceSelectionSync) ProtoMessage() {}

func (x *RobotPerformanceSelectionSync) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotPerformanceSelectionSync.ProtoReflect.Descriptor instead.
func (*RobotPerformanceSelectionSync) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{21}
}

func (x *RobotPerformanceSelectionSync) GetShooter() uint32 {
	if x != nil {
		return x.Shooter
	}
	return 0
}

func (x *RobotPerformanceSelectionSync) GetChassis() uint32 {
	if x != nil {
		return x.Chassis
	}
	return 0
}

// 英雄部署模式相关指令
// 自定义客户端→服务器
// 1Hz
type HeroDeployModeEventCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          uint32                 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"` // 部署模式指令，枚举值：0=退出部署模式，1=进入部署模式
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeroDeployModeEventCommand) Reset() {
	*x = HeroDeployModeEventCommand{}
	mi := &file_client_client_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeroDeployModeEventCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeroDeployModeEventCommand) ProtoMessage() {}

func (x *HeroDeployModeEventCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeroDeployModeEventCommand.ProtoReflect.Descriptor instead.
func (*HeroDeployModeEventCommand) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{22}
}

func (x *HeroDeployModeEventCommand) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

// 英雄部署模式状态同步
// 服务器→自定义客户端
// 1Hz
type DeployModeStatusSync struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CurrentDeployMode uint32                 `protobuf:"varint,1,opt,name=current_deploy_mode,json=currentDeployMode,proto3" json:"current_deploy_mode,omitempty"` // 当前部署模式状态，枚举值：0=未部署，1=已部署
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DeployModeStatusSync) Reset() {
	*x = DeployModeStatusSync{}
	mi := &file_client_client_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployModeStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployModeStatusSync) ProtoMessage() {}

func (x *DeployModeStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployModeStatusSync.ProtoReflect.Descriptor instead.
func (*DeployModeStatusSync) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{23}
}

func (x *DeployModeStatusSync) GetCurrentDeployMode() uint32 {
	if x != nil {
		return x.CurrentDeployMode
	}
	return 0
}

// 能量机关激活指令
// 自定义客户端→服务器
// 1Hz
type RuneActivateCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Activate      uint32                 `protobuf:"varint,1,opt,name=activate,proto3" json:"activate,omitempty"` // 激活指令，枚举值：1=开启能量机关激活流程，0=取消（仅1生效）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuneActivateCommand) Reset() {
	*x = RuneActivateCommand{}
	mi := &file_client_client_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuneActivateCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuneActivateCommand) ProtoMessage() {}

func (x *RuneActivateCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuneActivateCommand.ProtoReflect.Descriptor instead.
func (*RuneActivateCommand) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{24}
}

func (x *RuneActivateCommand) GetActivate() uint32 {
	if x != nil {
		return x.Activate
	}
	return 0
}

// 能量机关状态同步
// 服务器→自定义客户端
// 1Hz
type RuneStatusSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuneStatus    uint32                 `protobuf:"varint,1,opt,name=rune_status,json=runeStatus,proto3" json:"rune_status,omitempty"`          // 能量机关状态，枚举值：1=未激活，2=正在激活，3=已激活
	ActivatedArms uint32                 `protobuf:"varint,2,opt,name=activated_arms,json=activatedArms,proto3" json:"activated_arms,omitempty"` // 当前已激活的灯臂数量（0~总灯臂数，按赛事场地配置）
	AverageRings  uint32                 `protobuf:"varint,3,opt,name=average_rings,json=averageRings,proto3" json:"average_rings,omitempty"`    // 激活过程的平均环数（用于判定激活效果，按赛事规则计算）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuneStatusSync) Reset() {
	*x = RuneStatusSync{}
	mi := &file_client_client_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuneStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuneStatusSync) ProtoMessage() {}

func (x *RuneStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuneStatusSync.ProtoReflect.Descriptor instead.
func (*RuneStatusSync) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{25}
}

func (x *RuneStatusSync) GetRuneStatus() uint32 {
	if x != nil {
		return x.RuneStatus
	}
	return 0
}

func (x *RuneStatusSync) GetActivatedArms() uint32 {
	if x != nil {
		return x.ActivatedArms
	}
	return 0
}

func (x *RuneStatusSync) GetAverageRings() uint32 {
	if x != nil {
		return x.AverageRings
	}
	return 0
}

// 哨兵姿态相关信息同步
// 服务器→自定义客户端
// 1Hz
type SentinelStatusSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostureId     uint32                 `protobuf:"varint,1,opt,name=posture_id,json=postureId,proto3" json:"posture_id,omitempty"`    // 哨兵姿态ID，枚举值：1=进攻姿态，2=防御姿态，3=移动姿态
	IsWeakened    bool                   `protobuf:"varint,2,opt,name=is_weakened,json=isWeakened,proto3" json:"is_weakened,omitempty"` // 是否处于弱化状态（false=正常，true=弱化，如被飞镖命中后）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SentinelStatusSync) Reset() {
	*x = SentinelStatusSync{}
	mi := &file_client_client_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SentinelStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentinelStatusSync) ProtoMessage() {}

func (x *SentinelStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentinelStatusSync.ProtoReflect.Descriptor instead.
func (*SentinelStatusSync) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{26}
}

func (x *SentinelStatusSync) GetPostureId() uint32 {
	if x != nil {
		return x.PostureId
	}
	return 0
}

func (x *SentinelStatusSync) GetIsWeakened() bool {
	if x != nil {
		return x.IsWeakened
	}
	return false
}

// 飞镖控制指令
// 自定义客户端→服务器
// 1Hz
type DartCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint32                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 飞镖击打目标ID，枚举值：1=前哨站，2=基地固定目标，3=基地随机固定目标，4=基地随机移动目标，5=基地末端移动目标
	Open          bool                   `protobuf:"varint,2,opt,name=open,proto3" json:"open,omitempty"`                         // 飞镖闸门开关，枚举值：true=开启闸门，false=关闭闸门
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DartCommand) Reset() {
	*x = DartCommand{}
	mi := &file_client_client_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DartCommand) ProtoMessage() {}

func (x *DartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DartCommand.ProtoReflect.Descriptor instead.
func (*DartCommand) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{27}
}

func (x *DartCommand) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *DartCommand) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

// 飞镖目标选择状态同步
// 服务器→自定义客户端
// 1Hz
type DartSelectTargetStatusSync struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      uint32                 `protobuf:"varint,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // 当前选中的目标ID（枚举值同DartCommand.target_id）
	Open          bool                   `protobuf:"varint,2,opt,name=open,proto3" json:"open,omitempty"`                         // 当前闸门状态（true=开启，false=关闭）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DartSelectTargetStatusSync) Reset() {
	*x = DartSelectTargetStatusSync{}
	mi := &file_client_client_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DartSelectTargetStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DartSelectTargetStatusSync) ProtoMessage() {}

func (x *DartSelectTargetStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DartSelectTargetStatusSync.ProtoReflect.Descriptor instead.
func (*DartSelectTargetStatusSync) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{28}
}

func (x *DartSelectTargetStatusSync) GetTargetId() uint32 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

func (x *DartSelectTargetStatusSync) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

// 哨兵控制指令请求
// 自定义客户端→服务器
// 1Hz
type GuardCtrlCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint32                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // 指令编号，枚举值：0=无效指令，1=补血点补弹，2=补给站实体补弹，3=远程补弹，4=远程回血，5=确认免费复活，6=确认花费金币复活，7=地图标点，8=切换为进攻姿态，9=切换为防御姿态，10=切换为移动姿态
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardCtrlCommand) Reset() {
	*x = GuardCtrlCommand{}
	mi := &file_client_client_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardCtrlCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardCtrlCommand) ProtoMessage() {}

func (x *GuardCtrlCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardCtrlCommand.ProtoReflect.Descriptor instead.
func (*GuardCtrlCommand) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{29}
}

func (x *GuardCtrlCommand) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

// 哨兵控制指令结果反馈
// 服务器→自定义客户端
// 1Hz
type GuardCtrlResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint32                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`    // 对应的指令编号（与GuardCtrlCommand.command_id一一对应）
	ResultCode    uint32                 `protobuf:"varint,2,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"` // 执行结果码，枚举值：0=执行成功，1=参数无效，2=资源不足（如金币不够），3=状态不允许（如非待复活状态无法复活）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuardCtrlResult) Reset() {
	*x = GuardCtrlResult{}
	mi := &file_client_client_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuardCtrlResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuardCtrlResult) ProtoMessage() {}

func (x *GuardCtrlResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuardCtrlResult.ProtoReflect.Descriptor instead.
func (*GuardCtrlResult) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{30}
}

func (x *GuardCtrlResult) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

func (x *GuardCtrlResult) GetResultCode() uint32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

// 空中支援指令
// 自定义客户端→服务器
// 1Hz
type AirSupportCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     uint32                 `protobuf:"varint,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"` // 指令类型，枚举值：1=免费呼叫空中支援，2=花费金币呼叫空中支援（优先用免费时长），3=中断空中支援
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AirSupportCommand) Reset() {
	*x = AirSupportCommand{}
	mi := &file_client_client_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirSupportCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirSupportCommand) ProtoMessage() {}

func (x *AirSupportCommand) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirSupportCommand.ProtoReflect.Descriptor instead.
func (*AirSupportCommand) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{31}
}

func (x *AirSupportCommand) GetCommandId() uint32 {
	if x != nil {
		return x.CommandId
	}
	return 0
}

// 空中支援状态反馈
// 服务器→自定义客户端
// 1Hz
type AirSupportStatusSync struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AirsupportStatus uint32                 `protobuf:"varint,1,opt,name=airsupport_status,json=airsupportStatus,proto3" json:"airsupport_status,omitempty"` // 空中支援状态，枚举值：0=未进行空中支援，1=正在空中支援，2=被对方锁定无法开启
	LeftTime         uint32                 `protobuf:"varint,2,opt,name=left_time,json=leftTime,proto3" json:"left_time,omitempty"`                         // 免费空中支援剩余时间（单位：秒，无免费时长时为0）
	CostCoins        uint32                 `protobuf:"varint,3,opt,name=cost_coins,json=costCoins,proto3" json:"cost_coins,omitempty"`                      // 付费空中支援已花费金币（累计花费，无付费时为0）
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AirSupportStatusSync) Reset() {
	*x = AirSupportStatusSync{}
	mi := &file_client_client_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AirSupportStatusSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirSupportStatusSync) ProtoMessage() {}

func (x *AirSupportStatusSync) ProtoReflect() protoreflect.Message {
	mi := &file_client_client_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirSupportStatusSync.ProtoReflect.Descriptor instead.
func (*AirSupportStatusSync) Descriptor() ([]byte, []int) {
	return file_client_client_proto_rawDescGZIP(), []int{32}
}

func (x *AirSupportStatusSync) GetAirsupportStatus() uint32 {
	if x != nil {
		return x.AirsupportStatus
	}
	return 0
}

func (x *AirSupportStatusSync) GetLeftTime() uint32 {
	if x != nil {
		return x.LeftTime
	}
	return 0
}

func (x *AirSupportStatusSync) GetCostCoins() uint32 {
	if x != nil {
		return x.CostCoins
	}
	return 0
}

var File_client_client_proto protoreflect.FileDescriptor

const file_client_client_proto_rawDesc = "" +
	"\n" +
	"\x13client/client.proto\x12\x06client\"\x93\x02\n" +
	"\rRemoteControl\x12\x17\n" +
	"\amouse_x\x18\x01 \x01(\x05R\x06mouseX\x12\x17\n" +
	"\amouse_y\x18\x02 \x01(\x05R\x06mouseY\x12\x17\n" +
	"\amouse_z\x18\x03 \x01(\x05R\x06mouseZ\x12(\n" +
	"\x10left_button_down\x18\x04 \x01(\bR\x0eleftButtonDown\x12*\n" +
	"\x11right_button_down\x18\x05 \x01(\bR\x0frightButtonDown\x12%\n" +
	"\x0ekeyboard_value\x18\x06 \x01(\rR\rkeyboardValue\x12&\n" +
	"\x0fmid_button_down\x18\a \x01(\bR\rmidButtonDown\x12\x12\n" +
	"\x04data\x18\b \x01(\fR\x04data\"\xae\x02\n" +
	"\n" +
	"GameStatus\x12#\n" +
	"\rcurrent_round\x18\x01 \x01(\rR\fcurrentRound\x12!\n" +
	"\ftotal_rounds\x18\x02 \x01(\rR\vtotalRounds\x12\x1b\n" +
	"\tred_score\x18\x03 \x01(\rR\bredScore\x12\x1d\n" +
	"\n" +
	"blue_score\x18\x04 \x01(\rR\tblueScore\x12#\n" +
	"\rcurrent_stage\x18\x05 \x01(\rR\fcurrentStage\x12.\n" +
	"\x13stage_countdown_sec\x18\x06 \x01(\x05R\x11stageCountdownSec\x12*\n" +
	"\x11stage_elapsed_sec\x18\a \x01(\x05R\x0fstageElapsedSec\x12\x1b\n" +
	"\tis_paused\x18\b \x01(\bR\bisPaused\"\xe1\x02\n" +
	"\x10GlobalUnitStatus\x12\x1f\n" +
	"\vbase_health\x18\x01 \x01(\rR\n" +
	"baseHealth\x12\x1f\n" +
	"\vbase_status\x18\x02 \x01(\rR\n" +
	"baseStatus\x12\x1f\n" +
	"\vbase_shield\x18\x03 \x01(\rR\n" +
	"baseShield\x12%\n" +
	"\x0eoutpost_health\x18\x04 \x01(\rR\routpostHealth\x12%\n" +
	"\x0eoutpost_status\x18\x05 \x01(\rR\routpostStatus\x12!\n" +
	"\frobot_health\x18\x06 \x03(\rR\vrobotHealth\x12#\n" +
	"\rrobot_bullets\x18\a \x03(\x05R\frobotBullets\x12(\n" +
	"\x10total_damage_red\x18\b \x01(\rR\x0etotalDamageRed\x12*\n" +
	"\x11total_damage_blue\x18\t \x01(\rR\x0ftotalDamageBlue\"\xc4\x01\n" +
	"\x15GlobalLogisticsStatus\x12+\n" +
	"\x11remaining_economy\x18\x01 \x01(\rR\x10remainingEconomy\x124\n" +
	"\x16total_economy_obtained\x18\x02 \x01(\x04R\x14totalEconomyObtained\x12\x1d\n" +
	"\n" +
	"tech_level\x18\x03 \x01(\rR\ttechLevel\x12)\n" +
	"\x10encryption_level\x18\x04 \x01(\rR\x0fencryptionLevel\"i\n" +
	"\x16GlobalSpecialMechanism\x12!\n" +
	"\fmechanism_id\x18\x01 \x03(\rR\vmechanismId\x12,\n" +
	"\x12mechanism_time_sec\x18\x02 \x03(\x05R\x10mechanismTimeSec\"8\n" +
	"\x05Event\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x05R\aeventId\x12\x14\n" +
	"\x05param\x18\x02 \x01(\tR\x05param\"\xd3\x03\n" +
	"\x0fRobotInjuryStat\x12!\n" +
	"\ftotal_damage\x18\x01 \x01(\rR\vtotalDamage\x12)\n" +
	"\x10collision_damage\x18\x02 \x01(\rR\x0fcollisionDamage\x126\n" +
	"\x17small_projectile_damage\x18\x03 \x01(\rR\x15smallProjectileDamage\x126\n" +
	"\x17large_projectile_damage\x18\x04 \x01(\rR\x15largeProjectileDamage\x12,\n" +
	"\x12dart_splash_damage\x18\x05 \x01(\rR\x10dartSplashDamage\x122\n" +
	"\x15module_offline_damage\x18\x06 \x01(\rR\x13moduleOfflineDamage\x12.\n" +
	"\x13wifi_offline_damage\x18\a \x01(\rR\x11wifiOfflineDamage\x12%\n" +
	"\x0epenalty_damage\x18\b \x01(\rR\rpenaltyDamage\x12,\n" +
	"\x12server_kill_damage\x18\t \x01(\rR\x10serverKillDamage\x12\x1b\n" +
	"\tkiller_id\x18\n" +
	" \x01(\rR\bkillerId\"\xbe\x02\n" +
	"\x12RobotRespawnStatus\x12,\n" +
	"\x12is_pending_respawn\x18\x01 \x01(\bR\x10isPendingRespawn\x124\n" +
	"\x16total_respawn_progress\x18\x02 \x01(\rR\x14totalRespawnProgress\x128\n" +
	"\x18current_respawn_progress\x18\x03 \x01(\rR\x16currentRespawnProgress\x12(\n" +
	"\x10can_free_respawn\x18\x04 \x01(\bR\x0ecanFreeRespawn\x121\n" +
	"\x15gold_cost_for_respawn\x18\x05 \x01(\rR\x12goldCostForRespawn\x12-\n" +
	"\x13can_pay_for_respawn\x18\x06 \x01(\bR\x10canPayForRespawn\"\xab\x04\n" +
	"\x11RobotStaticStatus\x12)\n" +
	"\x10connection_state\x18\x01 \x01(\rR\x0fconnectionState\x12\x1f\n" +
	"\vfield_state\x18\x02 \x01(\rR\n" +
	"fieldState\x12\x1f\n" +
	"\valive_state\x18\x03 \x01(\rR\n" +
	"aliveState\x12\x19\n" +
	"\brobot_id\x18\x04 \x01(\rR\arobotId\x12\x1d\n" +
	"\n" +
	"robot_type\x18\x05 \x01(\rR\trobotType\x12<\n" +
	"\x1aperformance_system_shooter\x18\x06 \x01(\rR\x18performanceSystemShooter\x12<\n" +
	"\x1aperformance_system_chassis\x18\a \x01(\rR\x18performanceSystemChassis\x12\x14\n" +
	"\x05level\x18\b \x01(\rR\x05level\x12\x1d\n" +
	"\n" +
	"max_health\x18\t \x01(\rR\tmaxHealth\x12\x19\n" +
	"\bmax_heat\x18\n" +
	" \x01(\rR\amaxHeat\x12,\n" +
	"\x12heat_cooldown_rate\x18\v \x01(\x02R\x10heatCooldownRate\x12\x1b\n" +
	"\tmax_power\x18\f \x01(\rR\bmaxPower\x12*\n" +
	"\x11max_buffer_energy\x18\r \x01(\rR\x0fmaxBufferEnergy\x12,\n" +
	"\x12max_chassis_energy\x18\x0e \x01(\rR\x10maxChassisEnergy\"\xf7\x04\n" +
	"\x12RobotDynamicStatus\x12%\n" +
	"\x0ecurrent_health\x18\x01 \x01(\rR\rcurrentHealth\x12!\n" +
	"\fcurrent_heat\x18\x02 \x01(\x02R\vcurrentHeat\x129\n" +
	"\x19last_projectile_fire_rate\x18\x03 \x01(\x02R\x16lastProjectileFireRate\x124\n" +
	"\x16current_chassis_energy\x18\x04 \x01(\rR\x14currentChassisEnergy\x122\n" +
	"\x15current_buffer_energy\x18\x05 \x01(\rR\x13currentBufferEnergy\x12-\n" +
	"\x12current_experience\x18\x06 \x01(\rR\x11currentExperience\x124\n" +
	"\x16experience_for_upgrade\x18\a \x01(\rR\x14experienceForUpgrade\x126\n" +
	"\x17total_projectiles_fired\x18\b \x01(\rR\x15totalProjectilesFired\x12%\n" +
	"\x0eremaining_ammo\x18\t \x01(\rR\rremainingAmmo\x12'\n" +
	"\x10is_out_of_combat\x18\n" +
	" \x01(\bR\risOutOfCombat\x125\n" +
	"\x17out_of_combat_countdown\x18\v \x01(\rR\x14outOfCombatCountdown\x12&\n" +
	"\x0fcan_remote_heal\x18\f \x01(\bR\rcanRemoteHeal\x12&\n" +
	"\x0fcan_remote_ammo\x18\r \x01(\bR\rcanRemoteAmmo\"\xd1\x02\n" +
	"\x11RobotModuleStatus\x12#\n" +
	"\rpower_manager\x18\x01 \x01(\rR\fpowerManager\x12\x12\n" +
	"\x04rfid\x18\x02 \x01(\rR\x04rfid\x12\x1f\n" +
	"\vlight_strip\x18\x03 \x01(\rR\n" +
	"lightStrip\x12#\n" +
	"\rsmall_shooter\x18\x04 \x01(\rR\fsmallShooter\x12\x1f\n" +
	"\vbig_shooter\x18\x05 \x01(\rR\n" +
	"bigShooter\x12\x10\n" +
	"\x03uwb\x18\x06 \x01(\rR\x03uwb\x12\x14\n" +
	"\x05armor\x18\a \x01(\rR\x05armor\x12-\n" +
	"\x12video_transmission\x18\b \x01(\rR\x11videoTransmission\x12\x1c\n" +
	"\tcapacitor\x18\t \x01(\rR\tcapacitor\x12'\n" +
	"\x0fmain_controller\x18\n" +
	" \x01(\rR\x0emainController\"K\n" +
	"\rRobotPosition\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x10\n" +
	"\x03yaw\x18\x04 \x01(\x02R\x03yaw\"\xc6\x01\n" +
	"\x04Buff\x12\x19\n" +
	"\brobot_id\x18\x01 \x01(\rR\arobotId\x12\x1b\n" +
	"\tbuff_type\x18\x02 \x01(\rR\bbuffType\x12\x1d\n" +
	"\n" +
	"buff_level\x18\x03 \x01(\x05R\tbuffLevel\x12\"\n" +
	"\rbuff_max_time\x18\x04 \x01(\rR\vbuffMaxTime\x12$\n" +
	"\x0ebuff_left_time\x18\x05 \x01(\rR\fbuffLeftTime\x12\x1d\n" +
	"\n" +
	"msg_params\x18\x06 \x01(\tR\tmsgParams\"\x8a\x01\n" +
	"\vPenaltyInfo\x12!\n" +
	"\fpenalty_type\x18\x01 \x01(\rR\vpenaltyType\x12,\n" +
	"\x12penalty_effect_sec\x18\x02 \x01(\rR\x10penaltyEffectSec\x12*\n" +
	"\x11total_penalty_num\x18\x03 \x01(\rR\x0ftotalPenaltyNum\"\xcc\x01\n" +
	"\x11RobotPathPlanInfo\x12\x1c\n" +
	"\tintention\x18\x01 \x01(\rR\tintention\x12\x1e\n" +
	"\vstart_pos_x\x18\x02 \x01(\rR\tstartPosX\x12\x1e\n" +
	"\vstart_pos_y\x18\x03 \x01(\rR\tstartPosY\x12\x1d\n" +
	"\boffset_x\x18\x04 \x03(\x05B\x02\x10\x01R\aoffsetX\x12\x1d\n" +
	"\boffset_y\x18\x05 \x03(\x05B\x02\x10\x01R\aoffsetY\x12\x1b\n" +
	"\tsender_id\x18\x06 \x01(\rR\bsenderId\"\x88\x02\n" +
	"\x12MapClickInfoNotify\x12\x1e\n" +
	"\vis_send_all\x18\x01 \x01(\rR\tisSendAll\x12\x19\n" +
	"\brobot_id\x18\x02 \x01(\fR\arobotId\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x19\n" +
	"\benemy_id\x18\x04 \x01(\rR\aenemyId\x12\x14\n" +
	"\x05ascii\x18\x05 \x01(\rR\x05ascii\x12\x12\n" +
	"\x04type\x18\x06 \x01(\rR\x04type\x12\x19\n" +
	"\bscreen_x\x18\a \x01(\rR\ascreenX\x12\x19\n" +
	"\bscreen_y\x18\b \x01(\rR\ascreenY\x12\x13\n" +
	"\x05map_x\x18\t \x01(\x02R\x04mapX\x12\x13\n" +
	"\x05map_y\x18\n" +
	" \x01(\x02R\x04mapY\"\xc8\x01\n" +
	"\x11RaderInfoToClient\x12&\n" +
	"\x0ftarget_robot_id\x18\x01 \x01(\rR\rtargetRobotId\x12 \n" +
	"\ftarget_pos_x\x18\x02 \x01(\x02R\n" +
	"targetPosX\x12 \n" +
	"\ftarget_pos_y\x18\x03 \x01(\x02R\n" +
	"targetPosY\x12#\n" +
	"\rtorward_angle\x18\x04 \x01(\x02R\ftorwardAngle\x12\"\n" +
	"\ris_high_light\x18\x05 \x01(\rR\visHighLight\"%\n" +
	"\x0fCustomByteBlock\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"O\n" +
	"\x0fAssemblyCommand\x12\x1c\n" +
	"\toperation\x18\x01 \x01(\rR\toperation\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x02 \x01(\rR\n" +
	"difficulty\"k\n" +
	"\x17TechCoreMotionStateSync\x128\n" +
	"\x18maximum_difficulty_level\x18\x01 \x01(\rR\x16maximumDifficultyLevel\x12\x16\n" +
	"\x06status\x18\x02 \x01(\rR\x06status\"V\n" +
	" RobotPerformanceSelectionCommand\x12\x18\n" +
	"\ashooter\x18\x01 \x01(\rR\ashooter\x12\x18\n" +
	"\achassis\x18\x02 \x01(\rR\achassis\"S\n" +
	"\x1dRobotPerformanceSelectionSync\x12\x18\n" +
	"\ashooter\x18\x01 \x01(\rR\ashooter\x12\x18\n" +
	"\achassis\x18\x02 \x01(\rR\achassis\"0\n" +
	"\x1aHeroDeployModeEventCommand\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\rR\x04mode\"F\n" +
	"\x14DeployModeStatusSync\x12.\n" +
	"\x13current_deploy_mode\x18\x01 \x01(\rR\x11currentDeployMode\"1\n" +
	"\x13RuneActivateCommand\x12\x1a\n" +
	"\bactivate\x18\x01 \x01(\rR\bactivate\"}\n" +
	"\x0eRuneStatusSync\x12\x1f\n" +
	"\vrune_status\x18\x01 \x01(\rR\n" +
	"runeStatus\x12%\n" +
	"\x0eactivated_arms\x18\x02 \x01(\rR\ractivatedArms\x12#\n" +
	"\raverage_rings\x18\x03 \x01(\rR\faverageRings\"T\n" +
	"\x12SentinelStatusSync\x12\x1d\n" +
	"\n" +
	"posture_id\x18\x01 \x01(\rR\tpostureId\x12\x1f\n" +
	"\vis_weakened\x18\x02 \x01(\bR\n" +
	"isWeakened\">\n" +
	"\vDartCommand\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\rR\btargetId\x12\x12\n" +
	"\x04open\x18\x02 \x01(\bR\x04open\"M\n" +
	"\x1aDartSelectTargetStatusSync\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\rR\btargetId\x12\x12\n" +
	"\x04open\x18\x02 \x01(\bR\x04open\"1\n" +
	"\x10GuardCtrlCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\rR\tcommandId\"Q\n" +
	"\x0fGuardCtrlResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\rR\tcommandId\x12\x1f\n" +
	"\vresult_code\x18\x02 \x01(\rR\n" +
	"resultCode\"2\n" +
	"\x11AirSupportCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\rR\tcommandId\"\x7f\n" +
	"\x14AirSupportStatusSync\x12+\n" +
	"\x11airsupport_status\x18\x01 \x01(\rR\x10airsupportStatus\x12\x1b\n" +
	"\tleft_time\x18\x02 \x01(\rR\bleftTime\x12\x1d\n" +
	"\n" +
	"cost_coins\x18\x03 \x01(\rR\tcostCoinsB/Z-github.com/openrobosouls/rmproto/v2026/clientb\x06proto3"

var (
	file_client_client_proto_rawDescOnce sync.Once
	file_client_client_proto_rawDescData []byte
)

func file_client_client_proto_rawDescGZIP() []byte {
	file_client_client_proto_rawDescOnce.Do(func() {
		file_client_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_client_proto_rawDesc), len(file_client_client_proto_rawDesc)))
	})
	return file_client_client_proto_rawDescData
}

var file_client_client_proto_msgTypes = make([]protoimpl.MessageInfo, 33)
var file_client_client_proto_goTypes = []any{
	(*RemoteControl)(nil),                    // 0: client.RemoteControl
	(*GameStatus)(nil),                       // 1: client.GameStatus
	(*GlobalUnitStatus)(nil),                 // 2: client.GlobalUnitStatus
	(*GlobalLogisticsStatus)(nil),            // 3: client.GlobalLogisticsStatus
	(*GlobalSpecialMechanism)(nil),           // 4: client.GlobalSpecialMechanism
	(*Event)(nil),                            // 5: client.Event
	(*RobotInjuryStat)(nil),                  // 6: client.RobotInjuryStat
	(*RobotRespawnStatus)(nil),               // 7: client.RobotRespawnStatus
	(*RobotStaticStatus)(nil),                // 8: client.RobotStaticStatus
	(*RobotDynamicStatus)(nil),               // 9: client.RobotDynamicStatus
	(*RobotModuleStatus)(nil),                // 10: client.RobotModuleStatus
	(*RobotPosition)(nil),                    // 11: client.RobotPosition
	(*Buff)(nil),                             // 12: client.Buff
	(*PenaltyInfo)(nil),                      // 13: client.PenaltyInfo
	(*RobotPathPlanInfo)(nil),                // 14: client.RobotPathPlanInfo
	(*MapClickInfoNotify)(nil),               // 15: client.MapClickInfoNotify
	(*RaderInfoToClient)(nil),                // 16: client.RaderInfoToClient
	(*CustomByteBlock)(nil),                  // 17: client.CustomByteBlock
	(*AssemblyCommand)(nil),                  // 18: client.AssemblyCommand
	(*TechCoreMotionStateSync)(nil),          // 19: client.TechCoreMotionStateSync
	(*RobotPerformanceSelectionCommand)(nil), // 20: client.RobotPerformanceSelectionCommand
	(*RobotPerformanceSelectionSync)(nil),    // 21: client.RobotPerformanceSelectionSync
	(*HeroDeployModeEventCommand)(nil),       // 22: client.HeroDeployModeEventCommand
	(*DeployModeStatusSync)(nil),             // 23: client.DeployModeStatusSync
	(*RuneActivateCommand)(nil),              // 24: client.RuneActivateCommand
	(*RuneStatusSync)(nil),                   // 25: client.RuneStatusSync
	(*SentinelStatusSync)(nil),               // 26: client.SentinelStatusSync
	(*DartCommand)(nil),                      // 27: client.DartCommand
	(*DartSelectTargetStatusSync)(nil),       // 28: client.DartSelectTargetStatusSync
	(*GuardCtrlCommand)(nil),                 // 29: client.GuardCtrlCommand
	(*GuardCtrlResult)(nil),                  // 30: client.GuardCtrlResult
	(*AirSupportCommand)(nil),                // 31: client.AirSupportCommand
	(*AirSupportStatusSync)(nil),             // 32: client.AirSupportStatusSync
}
var file_client_client_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_client_proto_init() }
func file_client_client_proto_init() {
	if File_client_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_client_proto_rawDesc), len(file_client_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   33,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_client_proto_goTypes,
		DependencyIndexes: file_client_client_proto_depIdxs,
		MessageInfos:      file_client_client_proto_msgTypes,
	}.Build()
	File_client_client_proto = out.File
	file_client_client_proto_goTypes = nil
	file_client_client_proto_depIdxs = nil
}
