// auto generated by tdr 2.7.37, don't edit!
//
//	go code compiler
//	author: cowhuang@tencent.com
//
// create time: 2025-08-16 22:19:02
package client

import (
	"encoding/binary"
	"errors"

	"github.com/wintbiit/tsf4g/tdrcom"
)

// 红方英雄机器人
const IDRed1Hero int64 = 1

// 红方英雄机器人选手端
const ClientIDRed1Hero int64 = 0x0101

// 数据帧起始字节固定值
const SOF int64 = 0xA5
const (
	FrameHeaderBaseVersion    uint32 = 1
	FrameHeaderCurrentVersion uint32 = 1
)

// FrameHeader
type FrameHeader struct {
	Sof byte `tdr_field:"sof"`

	DataLength uint16 `tdr_field:"data_length"`

	Seq byte `tdr_field:"seq"`

	Crc8 byte `tdr_field:"crc8"`
}

func NewFrameHeader() *FrameHeader {
	obj := new(FrameHeader)
	obj.Init()
	return obj
}

func (this *FrameHeader) GetBaseVersion() uint32 {
	return FrameHeaderBaseVersion
}

func (this *FrameHeader) GetCurrentVersion() uint32 {
	return FrameHeaderCurrentVersion
}

func (this *FrameHeader) Init() {
	this.Sof = 0xA5

}

func (this *FrameHeader) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("FrameHeader Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *FrameHeader) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > FrameHeaderCurrentVersion {
		cutVer = FrameHeaderCurrentVersion
	}
	// check cut version
	if cutVer < FrameHeaderBaseVersion {
		return errors.New("FrameHeader cut version must large than FrameHeaderBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.Sof)
	if err != nil {
		return errors.New("FrameHeader.Sof pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.DataLength)
	if err != nil {
		return errors.New("FrameHeader.DataLength pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Seq)
	if err != nil {
		return errors.New("FrameHeader.Seq pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Crc8)
	if err != nil {
		return errors.New("FrameHeader.Crc8 pack error\n" + err.Error())
	}

	return nil
}

func (this *FrameHeader) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("FrameHeader data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *FrameHeader) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > FrameHeaderCurrentVersion {
		cutVer = FrameHeaderCurrentVersion
	}
	// check version
	if cutVer < FrameHeaderBaseVersion {
		errors.New("FrameHeader cut version must large than FrameHeaderBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.Sof)
	if err != nil {
		return errors.New("FrameHeader.Sof unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.DataLength)
	if err != nil {
		return errors.New("FrameHeader.DataLength unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Seq)
	if err != nil {
		return errors.New("FrameHeader.Seq unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Crc8)
	if err != nil {
		return errors.New("FrameHeader.Crc8 unpack error\n" + err.Error())
	}

	return err
}

// 比赛状态数据
const CmdGameState int64 = 0x0001

// 比赛结果数据
const CmdGameResult int64 = 0x0002

// 机器人血量数据
const CmdRobotHealth int64 = 0x0003

// 场地事件数据
const CmdEventData int64 = 0x0101

// 裁判警告数据
const CmdRefereeWarning int64 = 0x0104

// 飞镖发射相关数据
const CmdDartInfo int64 = 0x0105

// 机器人性能体系数据
const CmdRobotStatus int64 = 0x0201

// 实时底盘缓冲能量和射击热量数据
const CmdPowerHeatData int64 = 0x0202

// 机器人位置数据
const CmdRobotPosition int64 = 0x0203

// 机器人增益和底盘能量数据
const CmdBuffData int64 = 0x0204

// 实时射击数据
const CmdShootData int64 = 0x0207

// 允许发弹量
const CmdBulletAllowance int64 = 0x0208

// 机器人RFID模块状态
const CmdRFIDStatus int64 = 0x0209

// 飞镖选手端指令数据
const CmdDartClientCmd int64 = 0x020A

// 地面机器人位置数据
const CmdGroundRobotPos int64 = 0x020B

// 雷达标记进度数据
const CmdRadarMark int64 = 0x020C

// 哨兵自主决策信息同步
const CmdSentryInfo int64 = 0x020D

// 雷达自主决策信息同步
const CmdRadarInfo int64 = 0x020E

// 选手端小地图交互数据
const CmdClientMapInteraction int64 = 0x0303

// 键鼠遥控数据
const CmdKeyboardMouse int64 = 0x0304

// 数据帧中 data 的最大长度
const DataMaxLength int64 = 1024
const (
	FrameBaseVersion    uint32 = 1
	FrameCurrentVersion uint32 = 1
)

// Frame
type Frame struct {
	FrameHeader *FrameHeader `tdr_field:"frame_header"`

	CmdId uint16 `tdr_field:"cmd_id"`

	Data []byte `tdr_field:"data" tdr_count:"1024" tdr_refer:"FrameHeader.DataLength"`

	FrameTail uint16 `tdr_field:"frame_tail"`
}

func NewFrame() *Frame {
	obj := new(Frame)
	obj.Init()
	return obj
}

func (this *Frame) GetBaseVersion() uint32 {
	return FrameBaseVersion
}

func (this *Frame) GetCurrentVersion() uint32 {
	return FrameCurrentVersion
}

func (this *Frame) Init() {
	this.FrameHeader = NewFrameHeader()

}

func (this *Frame) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("Frame Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *Frame) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > FrameCurrentVersion {
		cutVer = FrameCurrentVersion
	}
	// check cut version
	if cutVer < FrameBaseVersion {
		return errors.New("Frame cut version must large than FrameBaseVersion\n")
	}

	var err error

	err = this.FrameHeader.PackTo(cutVer, w)
	if err != nil {
		return errors.New("Frame.FrameHeader pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.CmdId)
	if err != nil {
		return errors.New("Frame.CmdId pack error\n" + err.Error())
	}

	if this.FrameHeader.DataLength < 0 {
		return errors.New("Frame.Data's refer FrameHeader.DataLength should >= 0")
	}
	if this.FrameHeader.DataLength > 1024 {
		return errors.New("Frame.Data's refer FrameHeader.DataLength should <= count 1024")
	}
	if len(this.Data) < int(this.FrameHeader.DataLength) {
		return errors.New("Frame.Data's length should > FrameHeader.DataLength")
	}
	if this.FrameHeader.DataLength > 0 {
		referData := this.Data[:this.FrameHeader.DataLength]
		err = binary.Write(w, binary.BigEndian, referData)
		if err != nil {
			return errors.New("Frame.Data pack error\n" + err.Error())
		}
	}

	err = binary.Write(w, binary.BigEndian, this.FrameTail)
	if err != nil {
		return errors.New("Frame.FrameTail pack error\n" + err.Error())
	}

	return nil
}

func (this *Frame) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("Frame data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *Frame) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > FrameCurrentVersion {
		cutVer = FrameCurrentVersion
	}
	// check version
	if cutVer < FrameBaseVersion {
		errors.New("Frame cut version must large than FrameBaseVersion\n")
	}

	err = this.FrameHeader.UnpackFrom(cutVer, r)
	if err != nil {
		return errors.New("Frame.FrameHeader unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.CmdId)
	if err != nil {
		return errors.New("Frame.CmdId unpack error\n" + err.Error())
	}

	if this.FrameHeader.DataLength < 0 {
		return errors.New("Frame.Data's refer FrameHeader.DataLength should >= 0")
	}
	if this.FrameHeader.DataLength > 1024 {
		return errors.New("Frame.Data's refer FrameHeader.DataLength should <= count 1024")
	}

	if this.Data == nil {
		this.Data = make([]byte, int(this.FrameHeader.DataLength))
	}

	referData := this.Data[:this.FrameHeader.DataLength]
	err = binary.Read(r, binary.BigEndian, referData)
	if err != nil {
		return errors.New("Frame.Data pack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.FrameTail)
	if err != nil {
		return errors.New("Frame.FrameTail unpack error\n" + err.Error())
	}

	return err
}

// RoboMaster 机甲大师超级对抗赛
const GameTypeRoboMasterUC int64 = 1

// RoboMaster 机甲大师高校单项赛
const GameTypeRoboMasterCS int64 = 2

// ICRA RoboMaster 高校人工智能挑战赛
const GameTypeRoboMasterICRA int64 = 3

// RoboMaster 机甲大师高校联盟赛 3V3 对抗
const GameTypeRoboMasterUL int64 = 4

// RoboMaster 机甲大师高校联盟赛步兵对抗
const GameTypeRoboMasterULStandard int64 = 5

// 未开始比赛
const GameStageDefault int64 = 0

// 准备阶段
const GameStagePrepare int64 = 1

// 十五秒裁判系统自检阶段
const GameStageJudgeSystemCheck int64 = 2

// 五秒倒计时
const GameStageCountdown int64 = 3

// 比赛中
const GameStageRunning int64 = 4

// 比赛结算中
const GameStageEnd int64 = 5
const (
	GameStateDataBaseVersion    uint32 = 1
	GameStateDataCurrentVersion uint32 = 1
)

// GameStateData
type GameStateData struct {
	GameState byte `tdr_field:"game_state"`

	TimeRemaining uint16 `tdr_field:"time_remaining"`

	Timestamp uint64 `tdr_field:"timestamp"`
}

func NewGameStateData() *GameStateData {
	obj := new(GameStateData)
	obj.Init()
	return obj
}

func (this *GameStateData) GetBaseVersion() uint32 {
	return GameStateDataBaseVersion
}

func (this *GameStateData) GetCurrentVersion() uint32 {
	return GameStateDataCurrentVersion
}

func (this *GameStateData) Init() {

}

func (this *GameStateData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("GameStateData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *GameStateData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > GameStateDataCurrentVersion {
		cutVer = GameStateDataCurrentVersion
	}
	// check cut version
	if cutVer < GameStateDataBaseVersion {
		return errors.New("GameStateData cut version must large than GameStateDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.GameState)
	if err != nil {
		return errors.New("GameStateData.GameState pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.TimeRemaining)
	if err != nil {
		return errors.New("GameStateData.TimeRemaining pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Timestamp)
	if err != nil {
		return errors.New("GameStateData.Timestamp pack error\n" + err.Error())
	}

	return nil
}

func (this *GameStateData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("GameStateData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *GameStateData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > GameStateDataCurrentVersion {
		cutVer = GameStateDataCurrentVersion
	}
	// check version
	if cutVer < GameStateDataBaseVersion {
		errors.New("GameStateData cut version must large than GameStateDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.GameState)
	if err != nil {
		return errors.New("GameStateData.GameState unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.TimeRemaining)
	if err != nil {
		return errors.New("GameStateData.TimeRemaining unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Timestamp)
	if err != nil {
		return errors.New("GameStateData.Timestamp unpack error\n" + err.Error())
	}

	return err
}

// 平局
const GameResultDraw int64 = 0

// 红方胜利
const GameResultRedWin int64 = 1

// 蓝方胜利
const GameResultBlueWin int64 = 2
const (
	GameResultDataBaseVersion    uint32 = 1
	GameResultDataCurrentVersion uint32 = 1
)

// GameResultData
type GameResultData struct {
	GameResult byte `tdr_field:"game_result"`
}

func NewGameResultData() *GameResultData {
	obj := new(GameResultData)
	obj.Init()
	return obj
}

func (this *GameResultData) GetBaseVersion() uint32 {
	return GameResultDataBaseVersion
}

func (this *GameResultData) GetCurrentVersion() uint32 {
	return GameResultDataCurrentVersion
}

func (this *GameResultData) Init() {

}

func (this *GameResultData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("GameResultData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *GameResultData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > GameResultDataCurrentVersion {
		cutVer = GameResultDataCurrentVersion
	}
	// check cut version
	if cutVer < GameResultDataBaseVersion {
		return errors.New("GameResultData cut version must large than GameResultDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.GameResult)
	if err != nil {
		return errors.New("GameResultData.GameResult pack error\n" + err.Error())
	}

	return nil
}

func (this *GameResultData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("GameResultData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *GameResultData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > GameResultDataCurrentVersion {
		cutVer = GameResultDataCurrentVersion
	}
	// check version
	if cutVer < GameResultDataBaseVersion {
		errors.New("GameResultData cut version must large than GameResultDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.GameResult)
	if err != nil {
		return errors.New("GameResultData.GameResult unpack error\n" + err.Error())
	}

	return err
}

const (
	RobotHealthDataBaseVersion    uint32 = 1
	RobotHealthDataCurrentVersion uint32 = 1
)

// RobotHealthData
type RobotHealthData struct {
	Red1HeroHealth uint16 `tdr_field:"Red1HeroHealth"`

	Red2EngineerHealth uint16 `tdr_field:"Red2EngineerHealth"`

	Red3StandardHealth uint16 `tdr_field:"Red3StandardHealth"`

	Red4StandardHealth uint16 `tdr_field:"Red4StandardHealth"`

	Red5Preserved uint16 `tdr_field:"Red5Preserved"`

	Red7SentryHealth uint16 `tdr_field:"Red7SentryHealth"`

	RedOutpostHealth uint16 `tdr_field:"RedOutpostHealth"`

	RedBaseHealth uint16 `tdr_field:"RedBaseHealth"`

	Blue1HeroHealth uint16 `tdr_field:"Blue1HeroHealth"`

	Blue2EngineerHealth uint16 `tdr_field:"Blue2EngineerHealth"`

	Blue3StandardHealth uint16 `tdr_field:"Blue3StandardHealth"`

	Blue4StandardHealth uint16 `tdr_field:"Blue4StandardHealth"`

	Blue5Preserved uint16 `tdr_field:"Blue5Preserved"`

	Blue7SentryHealth uint16 `tdr_field:"Blue7SentryHealth"`

	BlueOutpostHealth uint16 `tdr_field:"BlueOutpostHealth"`

	BlueBaseHealth uint16 `tdr_field:"BlueBaseHealth"`
}

func NewRobotHealthData() *RobotHealthData {
	obj := new(RobotHealthData)
	obj.Init()
	return obj
}

func (this *RobotHealthData) GetBaseVersion() uint32 {
	return RobotHealthDataBaseVersion
}

func (this *RobotHealthData) GetCurrentVersion() uint32 {
	return RobotHealthDataCurrentVersion
}

func (this *RobotHealthData) Init() {

}

func (this *RobotHealthData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("RobotHealthData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *RobotHealthData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > RobotHealthDataCurrentVersion {
		cutVer = RobotHealthDataCurrentVersion
	}
	// check cut version
	if cutVer < RobotHealthDataBaseVersion {
		return errors.New("RobotHealthData cut version must large than RobotHealthDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.Red1HeroHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red1HeroHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Red2EngineerHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red2EngineerHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Red3StandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red3StandardHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Red4StandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red4StandardHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Red5Preserved)
	if err != nil {
		return errors.New("RobotHealthData.Red5Preserved pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Red7SentryHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red7SentryHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RedOutpostHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedOutpostHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RedBaseHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedBaseHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Blue1HeroHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue1HeroHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Blue2EngineerHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue2EngineerHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Blue3StandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue3StandardHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Blue4StandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue4StandardHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Blue5Preserved)
	if err != nil {
		return errors.New("RobotHealthData.Blue5Preserved pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Blue7SentryHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue7SentryHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BlueOutpostHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueOutpostHealth pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.BlueBaseHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueBaseHealth pack error\n" + err.Error())
	}

	return nil
}

func (this *RobotHealthData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("RobotHealthData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *RobotHealthData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > RobotHealthDataCurrentVersion {
		cutVer = RobotHealthDataCurrentVersion
	}
	// check version
	if cutVer < RobotHealthDataBaseVersion {
		errors.New("RobotHealthData cut version must large than RobotHealthDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.Red1HeroHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red1HeroHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Red2EngineerHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red2EngineerHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Red3StandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red3StandardHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Red4StandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red4StandardHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Red5Preserved)
	if err != nil {
		return errors.New("RobotHealthData.Red5Preserved unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Red7SentryHealth)
	if err != nil {
		return errors.New("RobotHealthData.Red7SentryHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RedOutpostHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedOutpostHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RedBaseHealth)
	if err != nil {
		return errors.New("RobotHealthData.RedBaseHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Blue1HeroHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue1HeroHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Blue2EngineerHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue2EngineerHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Blue3StandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue3StandardHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Blue4StandardHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue4StandardHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Blue5Preserved)
	if err != nil {
		return errors.New("RobotHealthData.Blue5Preserved unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Blue7SentryHealth)
	if err != nil {
		return errors.New("RobotHealthData.Blue7SentryHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BlueOutpostHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueOutpostHealth unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.BlueBaseHealth)
	if err != nil {
		return errors.New("RobotHealthData.BlueBaseHealth unpack error\n" + err.Error())
	}

	return err
}

const (
	EventDataBaseVersion    uint32 = 1
	EventDataCurrentVersion uint32 = 1
)

// EventData
type EventData struct {
	EventType byte `tdr_field:"event_type"`

	EventData byte `tdr_field:"event_data"`

	Reserved uint16 `tdr_field:"reserved"`
}

func NewEventData() *EventData {
	obj := new(EventData)
	obj.Init()
	return obj
}

func (this *EventData) GetBaseVersion() uint32 {
	return EventDataBaseVersion
}

func (this *EventData) GetCurrentVersion() uint32 {
	return EventDataCurrentVersion
}

func (this *EventData) Init() {

}

func (this *EventData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("EventData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *EventData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > EventDataCurrentVersion {
		cutVer = EventDataCurrentVersion
	}
	// check cut version
	if cutVer < EventDataBaseVersion {
		return errors.New("EventData cut version must large than EventDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.EventType)
	if err != nil {
		return errors.New("EventData.EventType pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.EventData)
	if err != nil {
		return errors.New("EventData.EventData pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Reserved)
	if err != nil {
		return errors.New("EventData.Reserved pack error\n" + err.Error())
	}

	return nil
}

func (this *EventData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("EventData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *EventData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > EventDataCurrentVersion {
		cutVer = EventDataCurrentVersion
	}
	// check version
	if cutVer < EventDataBaseVersion {
		errors.New("EventData cut version must large than EventDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.EventType)
	if err != nil {
		return errors.New("EventData.EventType unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.EventData)
	if err != nil {
		return errors.New("EventData.EventData unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Reserved)
	if err != nil {
		return errors.New("EventData.Reserved unpack error\n" + err.Error())
	}

	return err
}

const (
	RefereeWarningDataBaseVersion    uint32 = 1
	RefereeWarningDataCurrentVersion uint32 = 1
)

// RefereeWarningData
type RefereeWarningData struct {
	PenaltyLevel byte `tdr_field:"penalty_level"`

	OffenderId byte `tdr_field:"offender_id"`

	Count byte `tdr_field:"count"`
}

func NewRefereeWarningData() *RefereeWarningData {
	obj := new(RefereeWarningData)
	obj.Init()
	return obj
}

func (this *RefereeWarningData) GetBaseVersion() uint32 {
	return RefereeWarningDataBaseVersion
}

func (this *RefereeWarningData) GetCurrentVersion() uint32 {
	return RefereeWarningDataCurrentVersion
}

func (this *RefereeWarningData) Init() {

}

func (this *RefereeWarningData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("RefereeWarningData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *RefereeWarningData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > RefereeWarningDataCurrentVersion {
		cutVer = RefereeWarningDataCurrentVersion
	}
	// check cut version
	if cutVer < RefereeWarningDataBaseVersion {
		return errors.New("RefereeWarningData cut version must large than RefereeWarningDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.PenaltyLevel)
	if err != nil {
		return errors.New("RefereeWarningData.PenaltyLevel pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.OffenderId)
	if err != nil {
		return errors.New("RefereeWarningData.OffenderId pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Count)
	if err != nil {
		return errors.New("RefereeWarningData.Count pack error\n" + err.Error())
	}

	return nil
}

func (this *RefereeWarningData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("RefereeWarningData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *RefereeWarningData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > RefereeWarningDataCurrentVersion {
		cutVer = RefereeWarningDataCurrentVersion
	}
	// check version
	if cutVer < RefereeWarningDataBaseVersion {
		errors.New("RefereeWarningData cut version must large than RefereeWarningDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.PenaltyLevel)
	if err != nil {
		return errors.New("RefereeWarningData.PenaltyLevel unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.OffenderId)
	if err != nil {
		return errors.New("RefereeWarningData.OffenderId unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Count)
	if err != nil {
		return errors.New("RefereeWarningData.Count unpack error\n" + err.Error())
	}

	return err
}

const (
	DartInfoDataBaseVersion    uint32 = 1
	DartInfoDataCurrentVersion uint32 = 1
)

// DartInfoData
type DartInfoData struct {
	RemainingTime byte `tdr_field:"remaining_time"`

	DartInfo uint16 `tdr_field:"dart_info"`
}

func NewDartInfoData() *DartInfoData {
	obj := new(DartInfoData)
	obj.Init()
	return obj
}

func (this *DartInfoData) GetBaseVersion() uint32 {
	return DartInfoDataBaseVersion
}

func (this *DartInfoData) GetCurrentVersion() uint32 {
	return DartInfoDataCurrentVersion
}

func (this *DartInfoData) Init() {

}

func (this *DartInfoData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("DartInfoData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *DartInfoData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > DartInfoDataCurrentVersion {
		cutVer = DartInfoDataCurrentVersion
	}
	// check cut version
	if cutVer < DartInfoDataBaseVersion {
		return errors.New("DartInfoData cut version must large than DartInfoDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.RemainingTime)
	if err != nil {
		return errors.New("DartInfoData.RemainingTime pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.DartInfo)
	if err != nil {
		return errors.New("DartInfoData.DartInfo pack error\n" + err.Error())
	}

	return nil
}

func (this *DartInfoData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("DartInfoData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *DartInfoData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > DartInfoDataCurrentVersion {
		cutVer = DartInfoDataCurrentVersion
	}
	// check version
	if cutVer < DartInfoDataBaseVersion {
		errors.New("DartInfoData cut version must large than DartInfoDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.RemainingTime)
	if err != nil {
		return errors.New("DartInfoData.RemainingTime unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.DartInfo)
	if err != nil {
		return errors.New("DartInfoData.DartInfo unpack error\n" + err.Error())
	}

	return err
}

const (
	RobotStatusDataBaseVersion    uint32 = 1
	RobotStatusDataCurrentVersion uint32 = 1
)

// RobotStatusData
type RobotStatusData struct {
	RobotId byte `tdr_field:"robot_id"`

	RobotLevel byte `tdr_field:"robot_level"`

	CurrentHp uint16 `tdr_field:"current_hp"`

	MaxHp uint16 `tdr_field:"max_hp"`

	CoolingRate uint16 `tdr_field:"cooling_rate"`

	HeatLimit uint16 `tdr_field:"heat_limit"`

	PowerLimit uint16 `tdr_field:"power_limit"`

	PowerOutput byte `tdr_field:"power_output"`
}

func NewRobotStatusData() *RobotStatusData {
	obj := new(RobotStatusData)
	obj.Init()
	return obj
}

func (this *RobotStatusData) GetBaseVersion() uint32 {
	return RobotStatusDataBaseVersion
}

func (this *RobotStatusData) GetCurrentVersion() uint32 {
	return RobotStatusDataCurrentVersion
}

func (this *RobotStatusData) Init() {

}

func (this *RobotStatusData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("RobotStatusData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *RobotStatusData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > RobotStatusDataCurrentVersion {
		cutVer = RobotStatusDataCurrentVersion
	}
	// check cut version
	if cutVer < RobotStatusDataBaseVersion {
		return errors.New("RobotStatusData cut version must large than RobotStatusDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.RobotId)
	if err != nil {
		return errors.New("RobotStatusData.RobotId pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RobotLevel)
	if err != nil {
		return errors.New("RobotStatusData.RobotLevel pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.CurrentHp)
	if err != nil {
		return errors.New("RobotStatusData.CurrentHp pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.MaxHp)
	if err != nil {
		return errors.New("RobotStatusData.MaxHp pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.CoolingRate)
	if err != nil {
		return errors.New("RobotStatusData.CoolingRate pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.HeatLimit)
	if err != nil {
		return errors.New("RobotStatusData.HeatLimit pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.PowerLimit)
	if err != nil {
		return errors.New("RobotStatusData.PowerLimit pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.PowerOutput)
	if err != nil {
		return errors.New("RobotStatusData.PowerOutput pack error\n" + err.Error())
	}

	return nil
}

func (this *RobotStatusData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("RobotStatusData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *RobotStatusData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > RobotStatusDataCurrentVersion {
		cutVer = RobotStatusDataCurrentVersion
	}
	// check version
	if cutVer < RobotStatusDataBaseVersion {
		errors.New("RobotStatusData cut version must large than RobotStatusDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.RobotId)
	if err != nil {
		return errors.New("RobotStatusData.RobotId unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RobotLevel)
	if err != nil {
		return errors.New("RobotStatusData.RobotLevel unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.CurrentHp)
	if err != nil {
		return errors.New("RobotStatusData.CurrentHp unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.MaxHp)
	if err != nil {
		return errors.New("RobotStatusData.MaxHp unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.CoolingRate)
	if err != nil {
		return errors.New("RobotStatusData.CoolingRate unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.HeatLimit)
	if err != nil {
		return errors.New("RobotStatusData.HeatLimit unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.PowerLimit)
	if err != nil {
		return errors.New("RobotStatusData.PowerLimit unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.PowerOutput)
	if err != nil {
		return errors.New("RobotStatusData.PowerOutput unpack error\n" + err.Error())
	}

	return err
}

const (
	ShootDataBaseVersion    uint32 = 1
	ShootDataCurrentVersion uint32 = 1
)

// ShootData
type ShootData struct {
	BulletType byte `tdr_field:"bullet_type"`

	ShooterId byte `tdr_field:"shooter_id"`

	Frequency byte `tdr_field:"frequency"`

	Speed float32 `tdr_field:"speed"`
}

func NewShootData() *ShootData {
	obj := new(ShootData)
	obj.Init()
	return obj
}

func (this *ShootData) GetBaseVersion() uint32 {
	return ShootDataBaseVersion
}

func (this *ShootData) GetCurrentVersion() uint32 {
	return ShootDataCurrentVersion
}

func (this *ShootData) Init() {

}

func (this *ShootData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("ShootData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *ShootData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > ShootDataCurrentVersion {
		cutVer = ShootDataCurrentVersion
	}
	// check cut version
	if cutVer < ShootDataBaseVersion {
		return errors.New("ShootData cut version must large than ShootDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.BulletType)
	if err != nil {
		return errors.New("ShootData.BulletType pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.ShooterId)
	if err != nil {
		return errors.New("ShootData.ShooterId pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Frequency)
	if err != nil {
		return errors.New("ShootData.Frequency pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Speed)
	if err != nil {
		return errors.New("ShootData.Speed pack error\n" + err.Error())
	}

	return nil
}

func (this *ShootData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("ShootData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *ShootData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > ShootDataCurrentVersion {
		cutVer = ShootDataCurrentVersion
	}
	// check version
	if cutVer < ShootDataBaseVersion {
		errors.New("ShootData cut version must large than ShootDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.BulletType)
	if err != nil {
		return errors.New("ShootData.BulletType unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.ShooterId)
	if err != nil {
		return errors.New("ShootData.ShooterId unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Frequency)
	if err != nil {
		return errors.New("ShootData.Frequency unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Speed)
	if err != nil {
		return errors.New("ShootData.Speed unpack error\n" + err.Error())
	}

	return err
}

const (
	BulletAllowanceDataBaseVersion    uint32 = 1
	BulletAllowanceDataCurrentVersion uint32 = 1
)

// BulletAllowanceData
type BulletAllowanceData struct {
	Allowance17Mm uint16 `tdr_field:"allowance_17mm"`

	Allowance42Mm uint16 `tdr_field:"allowance_42mm"`

	Coins uint16 `tdr_field:"coins"`

	Reserved uint16 `tdr_field:"reserved"`
}

func NewBulletAllowanceData() *BulletAllowanceData {
	obj := new(BulletAllowanceData)
	obj.Init()
	return obj
}

func (this *BulletAllowanceData) GetBaseVersion() uint32 {
	return BulletAllowanceDataBaseVersion
}

func (this *BulletAllowanceData) GetCurrentVersion() uint32 {
	return BulletAllowanceDataCurrentVersion
}

func (this *BulletAllowanceData) Init() {

}

func (this *BulletAllowanceData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("BulletAllowanceData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *BulletAllowanceData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > BulletAllowanceDataCurrentVersion {
		cutVer = BulletAllowanceDataCurrentVersion
	}
	// check cut version
	if cutVer < BulletAllowanceDataBaseVersion {
		return errors.New("BulletAllowanceData cut version must large than BulletAllowanceDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.Allowance17Mm)
	if err != nil {
		return errors.New("BulletAllowanceData.Allowance17Mm pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Allowance42Mm)
	if err != nil {
		return errors.New("BulletAllowanceData.Allowance42Mm pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Coins)
	if err != nil {
		return errors.New("BulletAllowanceData.Coins pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Reserved)
	if err != nil {
		return errors.New("BulletAllowanceData.Reserved pack error\n" + err.Error())
	}

	return nil
}

func (this *BulletAllowanceData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("BulletAllowanceData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *BulletAllowanceData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > BulletAllowanceDataCurrentVersion {
		cutVer = BulletAllowanceDataCurrentVersion
	}
	// check version
	if cutVer < BulletAllowanceDataBaseVersion {
		errors.New("BulletAllowanceData cut version must large than BulletAllowanceDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.Allowance17Mm)
	if err != nil {
		return errors.New("BulletAllowanceData.Allowance17Mm unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Allowance42Mm)
	if err != nil {
		return errors.New("BulletAllowanceData.Allowance42Mm unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Coins)
	if err != nil {
		return errors.New("BulletAllowanceData.Coins unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Reserved)
	if err != nil {
		return errors.New("BulletAllowanceData.Reserved unpack error\n" + err.Error())
	}

	return err
}

const (
	RadarMarkDataBaseVersion    uint32 = 1
	RadarMarkDataCurrentVersion uint32 = 1
)

// RadarMarkData
type RadarMarkData struct {
	MarkProgress byte `tdr_field:"mark_progress"`
}

func NewRadarMarkData() *RadarMarkData {
	obj := new(RadarMarkData)
	obj.Init()
	return obj
}

func (this *RadarMarkData) GetBaseVersion() uint32 {
	return RadarMarkDataBaseVersion
}

func (this *RadarMarkData) GetCurrentVersion() uint32 {
	return RadarMarkDataCurrentVersion
}

func (this *RadarMarkData) Init() {

}

func (this *RadarMarkData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("RadarMarkData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *RadarMarkData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > RadarMarkDataCurrentVersion {
		cutVer = RadarMarkDataCurrentVersion
	}
	// check cut version
	if cutVer < RadarMarkDataBaseVersion {
		return errors.New("RadarMarkData cut version must large than RadarMarkDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.MarkProgress)
	if err != nil {
		return errors.New("RadarMarkData.MarkProgress pack error\n" + err.Error())
	}

	return nil
}

func (this *RadarMarkData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("RadarMarkData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *RadarMarkData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > RadarMarkDataCurrentVersion {
		cutVer = RadarMarkDataCurrentVersion
	}
	// check version
	if cutVer < RadarMarkDataBaseVersion {
		errors.New("RadarMarkData cut version must large than RadarMarkDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.MarkProgress)
	if err != nil {
		return errors.New("RadarMarkData.MarkProgress unpack error\n" + err.Error())
	}

	return err
}

const (
	SentryInfoDataBaseVersion    uint32 = 1
	SentryInfoDataCurrentVersion uint32 = 1
)

// SentryInfoData
type SentryInfoData struct {
	SentryInfo uint32 `tdr_field:"sentry_info"`

	SentryInfo2 uint16 `tdr_field:"sentry_info_2"`
}

func NewSentryInfoData() *SentryInfoData {
	obj := new(SentryInfoData)
	obj.Init()
	return obj
}

func (this *SentryInfoData) GetBaseVersion() uint32 {
	return SentryInfoDataBaseVersion
}

func (this *SentryInfoData) GetCurrentVersion() uint32 {
	return SentryInfoDataCurrentVersion
}

func (this *SentryInfoData) Init() {

}

func (this *SentryInfoData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("SentryInfoData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *SentryInfoData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > SentryInfoDataCurrentVersion {
		cutVer = SentryInfoDataCurrentVersion
	}
	// check cut version
	if cutVer < SentryInfoDataBaseVersion {
		return errors.New("SentryInfoData cut version must large than SentryInfoDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.SentryInfo)
	if err != nil {
		return errors.New("SentryInfoData.SentryInfo pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.SentryInfo2)
	if err != nil {
		return errors.New("SentryInfoData.SentryInfo2 pack error\n" + err.Error())
	}

	return nil
}

func (this *SentryInfoData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("SentryInfoData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *SentryInfoData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > SentryInfoDataCurrentVersion {
		cutVer = SentryInfoDataCurrentVersion
	}
	// check version
	if cutVer < SentryInfoDataBaseVersion {
		errors.New("SentryInfoData cut version must large than SentryInfoDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.SentryInfo)
	if err != nil {
		return errors.New("SentryInfoData.SentryInfo unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.SentryInfo2)
	if err != nil {
		return errors.New("SentryInfoData.SentryInfo2 unpack error\n" + err.Error())
	}

	return err
}

const (
	KeyboardMouseDataBaseVersion    uint32 = 1
	KeyboardMouseDataCurrentVersion uint32 = 1
)

// KeyboardMouseData
type KeyboardMouseData struct {
	MouseX int16 `tdr_field:"mouse_x"`

	MouseY int16 `tdr_field:"mouse_y"`

	MouseZ int16 `tdr_field:"mouse_z"`

	LeftButton byte `tdr_field:"left_button"`

	RightButton byte `tdr_field:"right_button"`

	KeyboardValue uint16 `tdr_field:"keyboard_value"`

	Reserved uint16 `tdr_field:"reserved"`
}

func NewKeyboardMouseData() *KeyboardMouseData {
	obj := new(KeyboardMouseData)
	obj.Init()
	return obj
}

func (this *KeyboardMouseData) GetBaseVersion() uint32 {
	return KeyboardMouseDataBaseVersion
}

func (this *KeyboardMouseData) GetCurrentVersion() uint32 {
	return KeyboardMouseDataCurrentVersion
}

func (this *KeyboardMouseData) Init() {

}

func (this *KeyboardMouseData) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("KeyboardMouseData Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *KeyboardMouseData) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > KeyboardMouseDataCurrentVersion {
		cutVer = KeyboardMouseDataCurrentVersion
	}
	// check cut version
	if cutVer < KeyboardMouseDataBaseVersion {
		return errors.New("KeyboardMouseData cut version must large than KeyboardMouseDataBaseVersion\n")
	}

	var err error

	err = binary.Write(w, binary.BigEndian, this.MouseX)
	if err != nil {
		return errors.New("KeyboardMouseData.MouseX pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.MouseY)
	if err != nil {
		return errors.New("KeyboardMouseData.MouseY pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.MouseZ)
	if err != nil {
		return errors.New("KeyboardMouseData.MouseZ pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.LeftButton)
	if err != nil {
		return errors.New("KeyboardMouseData.LeftButton pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.RightButton)
	if err != nil {
		return errors.New("KeyboardMouseData.RightButton pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.KeyboardValue)
	if err != nil {
		return errors.New("KeyboardMouseData.KeyboardValue pack error\n" + err.Error())
	}

	err = binary.Write(w, binary.BigEndian, this.Reserved)
	if err != nil {
		return errors.New("KeyboardMouseData.Reserved pack error\n" + err.Error())
	}

	return nil
}

func (this *KeyboardMouseData) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("KeyboardMouseData data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *KeyboardMouseData) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > KeyboardMouseDataCurrentVersion {
		cutVer = KeyboardMouseDataCurrentVersion
	}
	// check version
	if cutVer < KeyboardMouseDataBaseVersion {
		errors.New("KeyboardMouseData cut version must large than KeyboardMouseDataBaseVersion\n")
	}

	err = binary.Read(r, binary.BigEndian, &this.MouseX)
	if err != nil {
		return errors.New("KeyboardMouseData.MouseX unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.MouseY)
	if err != nil {
		return errors.New("KeyboardMouseData.MouseY unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.MouseZ)
	if err != nil {
		return errors.New("KeyboardMouseData.MouseZ unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.LeftButton)
	if err != nil {
		return errors.New("KeyboardMouseData.LeftButton unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.RightButton)
	if err != nil {
		return errors.New("KeyboardMouseData.RightButton unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.KeyboardValue)
	if err != nil {
		return errors.New("KeyboardMouseData.KeyboardValue unpack error\n" + err.Error())
	}

	err = binary.Read(r, binary.BigEndian, &this.Reserved)
	if err != nil {
		return errors.New("KeyboardMouseData.Reserved unpack error\n" + err.Error())
	}

	return err
}
