// Code generated by tdr 2.7.37, DO NOT EDIT.
//
//	go code compiler
//	author: assamluo@tencent.com
package s0

import (
	"encoding/binary"
	"errors"

	"github.com/wintbiit/tsf4g/tdrcom"
)

var endian = binary.LittleEndian

// 数据帧前缀字节
const PREFIX int64 = 241
const (
	HeaderBaseVersion    uint32 = 1
	HeaderCurrentVersion uint32 = 1
)

// Header
type Header struct {
	Prefix byte `tdr_field:"prefix"`

	ReceiverId byte `tdr_field:"receiver_id"`

	SenderId byte `tdr_field:"sender_id"`

	ProtoId uint16 `tdr_field:"proto_id"`

	DataLen uint16 `tdr_field:"data_len"`
}

func NewHeader() *Header {
	obj := new(Header)
	obj.Init()
	return obj
}

func (this *Header) GetBaseVersion() uint32 {
	return HeaderBaseVersion
}

func (this *Header) GetCurrentVersion() uint32 {
	return HeaderCurrentVersion
}

func (this *Header) Init() {

}

func (this *Header) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("Header Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *Header) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > HeaderCurrentVersion {
		cutVer = HeaderCurrentVersion
	}
	// check cut version
	if cutVer < HeaderBaseVersion {
		return errors.New("Header cut version must large than HeaderBaseVersion\n")
	}

	var err error

	err = binary.Write(w, endian, this.Prefix)
	if err != nil {
		return errors.New("Header.Prefix pack error\n" + err.Error())
	}

	err = binary.Write(w, endian, this.ReceiverId)
	if err != nil {
		return errors.New("Header.ReceiverId pack error\n" + err.Error())
	}

	err = binary.Write(w, endian, this.SenderId)
	if err != nil {
		return errors.New("Header.SenderId pack error\n" + err.Error())
	}

	err = binary.Write(w, endian, this.ProtoId)
	if err != nil {
		return errors.New("Header.ProtoId pack error\n" + err.Error())
	}

	err = binary.Write(w, endian, this.DataLen)
	if err != nil {
		return errors.New("Header.DataLen pack error\n" + err.Error())
	}

	return nil
}

func (this *Header) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("Header data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *Header) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > HeaderCurrentVersion {
		cutVer = HeaderCurrentVersion
	}
	// check version
	if cutVer < HeaderBaseVersion {
		errors.New("Header cut version must large than HeaderBaseVersion\n")
	}

	err = binary.Read(r, endian, &this.Prefix)
	if err != nil {
		return errors.New("Header.Prefix unpack error\n" + err.Error())
	}

	err = binary.Read(r, endian, &this.ReceiverId)
	if err != nil {
		return errors.New("Header.ReceiverId unpack error\n" + err.Error())
	}

	err = binary.Read(r, endian, &this.SenderId)
	if err != nil {
		return errors.New("Header.SenderId unpack error\n" + err.Error())
	}

	err = binary.Read(r, endian, &this.ProtoId)
	if err != nil {
		return errors.New("Header.ProtoId unpack error\n" + err.Error())
	}

	err = binary.Read(r, endian, &this.DataLen)
	if err != nil {
		return errors.New("Header.DataLen unpack error\n" + err.Error())
	}

	return err
}

const (
	FrameBaseVersion    uint32 = 1
	FrameCurrentVersion uint32 = 1
)

// Frame
type Frame struct {
	Header *Header `tdr_field:"header"`

	Data []byte `tdr_field:"data" tdr_count:"1024" tdr_refer:"Header.DataLen"`
}

func NewFrame() *Frame {
	obj := new(Frame)
	obj.Init()
	return obj
}

func (this *Frame) GetBaseVersion() uint32 {
	return FrameBaseVersion
}

func (this *Frame) GetCurrentVersion() uint32 {
	return FrameCurrentVersion
}

func (this *Frame) Init() {
	this.Header = NewHeader()

}

func (this *Frame) Pack(cutVer uint32) ([]byte, error) {
	w := tdrcom.NewWriter()
	if err := this.PackTo(cutVer, w); err != nil {
		return nil, errors.New("Frame Pack error\n" + err.Error())
	} else {
		return w.Bytes(), nil
	}
}

func (this *Frame) PackTo(cutVer uint32, w *tdrcom.Writer) error {
	// adjust cut version
	if cutVer == 0 || cutVer > FrameCurrentVersion {
		cutVer = FrameCurrentVersion
	}
	// check cut version
	if cutVer < FrameBaseVersion {
		return errors.New("Frame cut version must large than FrameBaseVersion\n")
	}

	var err error

	err = this.Header.PackTo(cutVer, w)
	if err != nil {
		return errors.New("Frame.Header pack error\n" + err.Error())
	}

	if this.Header.DataLen < 0 {
		return errors.New("Frame.Data's refer Header.DataLen should >= 0")
	}
	if this.Header.DataLen > 1024 {
		return errors.New("Frame.Data's refer Header.DataLen should <= count 1024")
	}
	if len(this.Data) < int(this.Header.DataLen) {
		return errors.New("Frame.Data's length should > Header.DataLen")
	}
	if this.Header.DataLen > 0 {
		referData := this.Data[:this.Header.DataLen]
		err = binary.Write(w, endian, referData)
		if err != nil {
			return errors.New("Frame.Data pack error\n" + err.Error())
		}
	}

	return nil
}

func (this *Frame) Unpack(cutVer uint32, data []byte) error {
	if nil == data {
		return errors.New("Frame data is nil")
	}
	return this.UnpackFrom(cutVer, tdrcom.NewReader(data))
}

func (this *Frame) UnpackFrom(cutVer uint32, r *tdrcom.Reader) error {
	var err error = nil
	// adjust version
	if cutVer == 0 || cutVer > FrameCurrentVersion {
		cutVer = FrameCurrentVersion
	}
	// check version
	if cutVer < FrameBaseVersion {
		errors.New("Frame cut version must large than FrameBaseVersion\n")
	}

	err = this.Header.UnpackFrom(cutVer, r)
	if err != nil {
		return errors.New("Frame.Header unpack error\n" + err.Error())
	}

	if this.Header.DataLen < 0 {
		return errors.New("Frame.Data's refer Header.DataLen should >= 0")
	}
	if this.Header.DataLen > 1024 {
		return errors.New("Frame.Data's refer Header.DataLen should <= count 1024")
	}

	if this.Data == nil {
		this.Data = make([]byte, int(this.Header.DataLen))
	}

	referData := this.Data[:this.Header.DataLen]
	err = binary.Read(r, endian, referData)
	if err != nil {
		return errors.New("Frame.Data pack error\n" + err.Error())
	}

	return err
}
