// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: s99.proto

package s99

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RobotStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RobotStatus) Reset() {
	*x = RobotStatus{}
	mi := &file_s99_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RobotStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RobotStatus) ProtoMessage() {}

func (x *RobotStatus) ProtoReflect() protoreflect.Message {
	mi := &file_s99_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RobotStatus.ProtoReflect.Descriptor instead.
func (*RobotStatus) Descriptor() ([]byte, []int) {
	return file_s99_proto_rawDescGZIP(), []int{0}
}

var File_s99_proto protoreflect.FileDescriptor

const file_s99_proto_rawDesc = "" +
	"\n" +
	"\ts99.proto\x12\x03s99\"\r\n" +
	"\vRobotStatusB\bZ\x06./;s99b\x06proto3"

var (
	file_s99_proto_rawDescOnce sync.Once
	file_s99_proto_rawDescData []byte
)

func file_s99_proto_rawDescGZIP() []byte {
	file_s99_proto_rawDescOnce.Do(func() {
		file_s99_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_s99_proto_rawDesc), len(file_s99_proto_rawDesc)))
	})
	return file_s99_proto_rawDescData
}

var file_s99_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_s99_proto_goTypes = []any{
	(*RobotStatus)(nil), // 0: s99.RobotStatus
}
var file_s99_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_s99_proto_init() }
func file_s99_proto_init() {
	if File_s99_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_s99_proto_rawDesc), len(file_s99_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_s99_proto_goTypes,
		DependencyIndexes: file_s99_proto_depIdxs,
		MessageInfos:      file_s99_proto_msgTypes,
	}.Build()
	File_s99_proto = out.File
	file_s99_proto_goTypes = nil
	file_s99_proto_depIdxs = nil
}
